package integration.program.test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import integration.program.compile.CompileAndRun;
import integration.program.compile.CompileAndRunImpl;
import integration.program.model.CaseModel;
import integration.program.model.CompileResult;
import integration.program.model.RunResult;

public class Test {

	public static void main(String[] args) throws IOException, InterruptedException {
		//testCompile();
		testRun();
	}

	// ≤‚ ‘±‡“Î
	public static void  testCompile() throws IOException, InterruptedException {

		CompileAndRun compileCode = new CompileAndRunImpl();

		CompileResult result = compileCode.CompileCode("Solution.java");

		System.out.println(result.getResultCode());
		for (String ss : result.getResultString()) {
			System.out.println(ss);
		}

	}

	// ≤‚ ‘‘À––
	public static void testRun() throws IOException, InterruptedException {

		List<RunResult> runResultList = new ArrayList<RunResult>();
		List<CaseModel> caseModelList = new ArrayList<CaseModel>();
		CaseModel case1 = new CaseModel();
		CaseModel case2 = new CaseModel();
		CaseModel case3 = new CaseModel();
		case1.setInput("5\r\n" + "amy 100\r\n" + "david 100\r\n" + "heraldo 50\r\n" + "aakansha 75\r\n" + "aleksa 150");

		case1.setOutput("aleksa 150\r\n" + "amy 100\r\n" + "david 100\r\n" + "aakansha 75\r\n" + "heraldo 50");

		case2.setInput("1000\r\n" + "cebebb 10\r\n" + "bdfefa 23\r\n" + "bee 6\r\n" + "ddbcb 20\r\n" + "fea 1\r\n"
				+ "bd 3\r\n" + "cecd 12\r\n" + "bb 1\r\n" + "aafde 12\r\n" + "dd 8\r\n" + "edcccf 3\r\n"
				+ "fffdfce 19\r\n" + "efdc 19\r\n" + "a 10\r\n" + "cda 24\r\n" + "cddfd 18\r\n" + "afad 17\r\n"
				+ "efafbfc 6\r\n" + "dbcae 0\r\n" + "eafab 12\r\n" + "cdefdf 3\r\n" + "dfadadf 8\r\n" + "c 24\r\n"
				+ "bb 24\r\n" + "fbbfceb 9\r\n" + "fcfccda 18\r\n" + "dddaab 2\r\n" + "b 18\r\n" + "cecddf 20\r\n"
				+ "e 4\r\n" + "d 1\r\n" + "e 24\r\n" + "eddfabf 22\r\n" + "eace 20\r\n" + "adce 7\r\n" + "ffacad 11\r\n"
				+ "bccdf 9\r\n" + "efe 6\r\n" + "fba 22\r\n" + "adfebd 10\r\n" + "e 11\r\n" + "bddaf 22\r\n"
				+ "cd 19\r\n" + "c 15\r\n" + "eebeeee 8\r\n" + "bbbd 22\r\n" + "da 16\r\n" + "cddaca 0\r\n"
				+ "fadfc 13\r\n" + "eecaba 1\r\n" + "acadaea 6\r\n" + "dc 24\r\n" + "aed 1\r\n" + "ac 8\r\n"
				+ "aa 5\r\n" + "adba 21\r\n" + "cdeaa 9\r\n" + "afd 12\r\n" + "d 14\r\n" + "adeafb 18\r\n"
				+ "dadebdb 15\r\n" + "d 20\r\n" + "ddfbb 11\r\n" + "eddcbee 21\r\n" + "f 16\r\n" + "aeeef 19\r\n"
				+ "adb 23\r\n" + "caddba 20\r\n" + "bffb 3\r\n" + "a 22\r\n" + "eafcecb 5\r\n" + "fffefbd 21\r\n"
				+ "ca 11\r\n" + "aedb 22\r\n" + "ffcdff 13\r\n" + "bfdbe 9\r\n" + "bb 18\r\n" + "baeaec 9\r\n"
				+ "edabc 7\r\n" + "abcddc 1\r\n" + "bf 4\r\n" + "e 21\r\n" + "aa 4\r\n" + "eefc 14\r\n"
				+ "fdccfd 23\r\n" + "ddd 14\r\n" + "bb 22\r\n" + "fbcab 9\r\n" + "dfaaccb 18\r\n" + "dbcabd 8\r\n"
				+ "abfaacb 1\r\n" + "eacfc 22\r\n" + "aeecfee 14\r\n" + "abbdde 18\r\n" + "bcd 12\r\n" + "de 24\r\n"
				+ "ecbbf 7\r\n" + "dbf 18\r\n" + "afafadd 0\r\n" + "adfd 24\r\n" + "eacfef 21\r\n" + "efffbc 15\r\n"
				+ "ca 14\r\n" + "eec 3\r\n" + "adbcf 17\r\n" + "feadbe 13\r\n" + "edddfcf 16\r\n" + "cfcabcf 4\r\n"
				+ "a 22\r\n" + "cc 9\r\n" + "aaefacb 14\r\n" + "cbfbfdd 22\r\n" + "bd 24\r\n" + "dabfac 12\r\n"
				+ "f 7\r\n" + "df 11\r\n" + "ebaabdc 24\r\n" + "dcdffaa 20\r\n" + "faefade 14\r\n" + "ceefdd 20\r\n"
				+ "c 13\r\n" + "aabcb 12\r\n" + "acbebf 9\r\n" + "aedb 9\r\n" + "fbbaefc 23\r\n" + "dbcccca 22\r\n"
				+ "ab 22\r\n" + "ebbea 13\r\n" + "dcbedb 0\r\n" + "bfe 2\r\n" + "ffbbeb 8\r\n" + "abeeb 22\r\n"
				+ "bc 15\r\n" + "cf 6\r\n" + "bedaefd 9\r\n" + "bcdfd 21\r\n" + "be 22\r\n" + "fde 0\r\n"
				+ "dafcecb 17\r\n" + "ceb 18\r\n" + "feb 11\r\n" + "cdfbbdf 10\r\n" + "dc 2\r\n" + "abdccc 19\r\n"
				+ "efe 15\r\n" + "c 15\r\n" + "dcf 18\r\n" + "aaafc 4\r\n" + "dab 24\r\n" + "ce 0\r\n" + "f 15\r\n"
				+ "cebfa 12\r\n" + "ba 16\r\n" + "d 12\r\n" + "dda 6\r\n" + "d 13\r\n" + "aeacad 15\r\n"
				+ "cefebdc 7\r\n" + "cccdaf 11\r\n" + "fffad 0\r\n" + "bebfbdb 4\r\n" + "aaaccce 8\r\n" + "efce 7\r\n"
				+ "baacefb 6\r\n" + "ad 18\r\n" + "efacd 1\r\n" + "dbffbdc 13\r\n" + "fd 18\r\n" + "cbbba 13\r\n"
				+ "aafcecc 22\r\n" + "ff 3\r\n" + "e 21\r\n" + "bfc 19\r\n" + "fa 2\r\n" + "f 10\r\n" + "daddac 18\r\n"
				+ "d 7\r\n" + "cfedcac 4\r\n" + "ae 19\r\n" + "beebb 8\r\n" + "eee 14\r\n" + "ff 15\r\n" + "d 14\r\n"
				+ "bafdaa 10\r\n" + "ab 15\r\n" + "a 3\r\n" + "b 17\r\n" + "ddd 14\r\n" + "aec 20\r\n" + "ecb 2\r\n"
				+ "acb 22\r\n" + "beeabe 6\r\n" + "afd 19\r\n" + "ead 21\r\n" + "ed 17\r\n" + "fcfabfc 22\r\n"
				+ "bea 20\r\n" + "cabaac 6\r\n" + "a 17\r\n" + "fbecce 5\r\n" + "bae 13\r\n" + "dacb 20\r\n"
				+ "caedfcf 6\r\n" + "eeaddce 4\r\n" + "edf 16\r\n" + "dfcdbef 21\r\n" + "aeada 6\r\n" + "fbedfba 14\r\n"
				+ "e 2\r\n" + "cd 14\r\n" + "cebdae 11\r\n" + "cecfda 6\r\n" + "ffde 16\r\n" + "daec 14\r\n"
				+ "acdaac 15\r\n" + "bcadedd 10\r\n" + "cfa 23\r\n" + "d 16\r\n" + "afcd 20\r\n" + "dcedc 7\r\n"
				+ "eff 7\r\n" + "e 0\r\n" + "dca 12\r\n" + "beeac 17\r\n" + "dbedcaf 1\r\n" + "ededdc 17\r\n"
				+ "c 2\r\n" + "cc 13\r\n" + "bbbacae 20\r\n" + "cacaaa 2\r\n" + "b 18\r\n" + "cea 19\r\n" + "ccdd 9\r\n"
				+ "efaeba 24\r\n" + "fce 16\r\n" + "e 5\r\n" + "abca 17\r\n" + "ed 8\r\n" + "fa 22\r\n" + "fefdaa 0\r\n"
				+ "e 7\r\n" + "dcc 7\r\n" + "aea 21\r\n" + "cca 4\r\n" + "cceec 11\r\n" + "ceacfbb 3\r\n" + "cfdb 9\r\n"
				+ "ff 15\r\n" + "b 2\r\n" + "eecaa 20\r\n" + "b 15\r\n" + "fefeeed 13\r\n" + "deac 24\r\n"
				+ "fedbccf 17\r\n" + "eeab 9\r\n" + "ccfbad 24\r\n" + "acdeafb 1\r\n" + "f 15\r\n" + "abbc 11\r\n"
				+ "fc 1\r\n" + "f 17\r\n" + "efdfdfd 18\r\n" + "fefac 14\r\n" + "b 22\r\n" + "bea 9\r\n"
				+ "ffbce 19\r\n" + "cbcb 12\r\n" + "cacbfac 24\r\n" + "ab 14\r\n" + "cccffae 7\r\n" + "daf 5\r\n"
				+ "bdcbfcc 12\r\n" + "c 13\r\n" + "cbaf 22\r\n" + "fdf 24\r\n" + "dcb 15\r\n" + "a 23\r\n" + "a 8\r\n"
				+ "baebbed 15\r\n" + "dbdde 11\r\n" + "cafdbf 0\r\n" + "cd 23\r\n" + "dbe 14\r\n" + "cebeabb 8\r\n"
				+ "ceddf 17\r\n" + "cf 4\r\n" + "ebcffe 0\r\n" + "aedc 19\r\n" + "becac 20\r\n" + "aeedcca 1\r\n"
				+ "adeccbe 19\r\n" + "efaaadf 6\r\n" + "eea 14\r\n" + "edaed 21\r\n" + "aecc 20\r\n" + "dcaaa 7\r\n"
				+ "f 16\r\n" + "c 24\r\n" + "a 16\r\n" + "fab 13\r\n" + "aeddf 9\r\n" + "bebda 16\r\n" + "f 0\r\n"
				+ "ebcecb 10\r\n" + "ccf 0\r\n" + "bcceffc 0\r\n" + "aebeefd 18\r\n" + "fdacdff 18\r\n"
				+ "bfedaad 23\r\n" + "c 10\r\n" + "add 23\r\n" + "ffdf 8\r\n" + "cc 16\r\n" + "cbfebc 15\r\n"
				+ "aafddb 0\r\n" + "bdeb 22\r\n" + "eaabea 1\r\n" + "fdacfbc 0\r\n" + "dfcedd 22\r\n" + "dcfcfbb 12\r\n"
				+ "acabbd 20\r\n" + "ac 10\r\n" + "ced 21\r\n" + "ccabeb 0\r\n" + "efc 9\r\n" + "cdcacbd 20\r\n"
				+ "bc 24\r\n" + "eef 5\r\n" + "becacdc 24\r\n" + "baaba 3\r\n" + "aed 2\r\n" + "efdabfd 3\r\n"
				+ "eabaad 1\r\n" + "efbea 17\r\n" + "b 15\r\n" + "fae 21\r\n" + "be 24\r\n" + "e 12\r\n"
				+ "bbeabfb 15\r\n" + "fbbcba 9\r\n" + "df 16\r\n" + "dbecda 4\r\n" + "e 9\r\n" + "ffe 14\r\n"
				+ "f 6\r\n" + "dfcf 13\r\n" + "dfdcdf 16\r\n" + "dffbbb 23\r\n" + "fbbeedd 22\r\n" + "acfdf 5\r\n"
				+ "eb 20\r\n" + "afdb 9\r\n" + "de 19\r\n" + "efadd 21\r\n" + "eccdcfa 6\r\n" + "b 17\r\n" + "bc 14\r\n"
				+ "d 9\r\n" + "eacd 23\r\n" + "c 4\r\n" + "d 2\r\n" + "cfaffff 11\r\n" + "fa 21\r\n" + "dcceaa 4\r\n"
				+ "deefec 21\r\n" + "feecebb 23\r\n" + "ecd 18\r\n" + "d 5\r\n" + "d 23\r\n" + "efcfb 11\r\n"
				+ "da 8\r\n" + "fcb 10\r\n" + "cea 21\r\n" + "dacecc 19\r\n" + "edbb 16\r\n" + "cffafcd 1\r\n"
				+ "ffdbd 2\r\n" + "ae 10\r\n" + "abcae 14\r\n" + "aaceb 17\r\n" + "fca 11\r\n" + "cf 23\r\n"
				+ "febf 21\r\n" + "ad 13\r\n" + "aced 12\r\n" + "dfccee 20\r\n" + "ccc 12\r\n" + "deebdee 17\r\n"
				+ "acea 24\r\n" + "bfeeeeb 9\r\n" + "aacca 21\r\n" + "dda 18\r\n" + "efcbfd 23\r\n" + "ff 0\r\n"
				+ "bbddae 7\r\n" + "ceddff 10\r\n" + "ffccff 11\r\n" + "ccef 9\r\n" + "eeba 20\r\n" + "cfcee 6\r\n"
				+ "bc 14\r\n" + "fdcfafc 7\r\n" + "cf 24\r\n" + "fb 8\r\n" + "bfcdcca 7\r\n" + "fe 4\r\n" + "edd 0\r\n"
				+ "bc 13\r\n" + "bff 10\r\n" + "facab 9\r\n" + "dedbaae 24\r\n" + "acbb 5\r\n" + "cbed 13\r\n"
				+ "cfbbfd 7\r\n" + "daffb 20\r\n" + "f 6\r\n" + "ddecede 6\r\n" + "cbbeea 5\r\n" + "dbdfeb 15\r\n"
				+ "adaf 20\r\n" + "b 6\r\n" + "dfebc 24\r\n" + "dcab 21\r\n" + "fddaaf 8\r\n" + "cbfa 14\r\n"
				+ "fffa 23\r\n" + "e 1\r\n" + "fec 15\r\n" + "bfbe 12\r\n" + "ebbfcbe 1\r\n" + "d 10\r\n" + "c 0\r\n"
				+ "faf 16\r\n" + "caf 19\r\n" + "e 7\r\n" + "dacbfdf 6\r\n" + "dba 20\r\n" + "ed 22\r\n" + "aea 15\r\n"
				+ "ab 7\r\n" + "cd 12\r\n" + "ae 23\r\n" + "bbea 21\r\n" + "fbabed 10\r\n" + "cafcb 4\r\n" + "eac 0\r\n"
				+ "dbca 20\r\n" + "fdbd 6\r\n" + "ed 20\r\n" + "fcb 21\r\n" + "adbedfe 11\r\n" + "cc 9\r\n" + "c 5\r\n"
				+ "af 7\r\n" + "cbf 22\r\n" + "ac 20\r\n" + "beadfe 11\r\n" + "afbc 13\r\n" + "eb 0\r\n" + "badc 14\r\n"
				+ "cfdcabb 14\r\n" + "becf 7\r\n" + "ddffceb 4\r\n" + "cdfaa 21\r\n" + "cee 6\r\n" + "dda 16\r\n"
				+ "eacb 10\r\n" + "ebdfddd 19\r\n" + "ebdeae 18\r\n" + "a 24\r\n" + "bcfb 8\r\n" + "afc 8\r\n"
				+ "fbfeecf 11\r\n" + "dfdad 24\r\n" + "fadeb 14\r\n" + "bcd 5\r\n" + "dbd 1\r\n" + "ccecfcb 17\r\n"
				+ "e 23\r\n" + "effca 18\r\n" + "ddc 9\r\n" + "ff 6\r\n" + "aaacb 15\r\n" + "aefbdc 5\r\n"
				+ "aadaafb 10\r\n" + "cfbbeb 20\r\n" + "f 3\r\n" + "a 21\r\n" + "ffea 9\r\n" + "dae 12\r\n"
				+ "ebcd 0\r\n" + "f 22\r\n" + "ffbfca 18\r\n" + "fe 15\r\n" + "edcfd 3\r\n" + "f 17\r\n" + "bcbef 5\r\n"
				+ "cef 12\r\n" + "e 11\r\n" + "fcb 7\r\n" + "dec 17\r\n" + "dd 24\r\n" + "bfbdfe 7\r\n" + "abaf 1\r\n"
				+ "bdbe 2\r\n" + "afdeabf 2\r\n" + "e 23\r\n" + "ddfcbac 15\r\n" + "ce 11\r\n" + "daf 19\r\n"
				+ "dccb 13\r\n" + "aedc 21\r\n" + "fede 17\r\n" + "c 23\r\n" + "eacf 12\r\n" + "dbaa 8\r\n"
				+ "adfa 15\r\n" + "bfc 23\r\n" + "ecb 19\r\n" + "ebc 0\r\n" + "ddc 20\r\n" + "bbcf 17\r\n"
				+ "bfacbc 17\r\n" + "bd 5\r\n" + "c 1\r\n" + "ecc 20\r\n" + "ffc 6\r\n" + "dfebefa 2\r\n" + "c 24\r\n"
				+ "cac 13\r\n" + "dadfedb 14\r\n" + "eee 12\r\n" + "abdbf 22\r\n" + "bfbffcf 16\r\n" + "fd 15\r\n"
				+ "cec 12\r\n" + "afbcb 18\r\n" + "cbbffa 24\r\n" + "aebcdbd 14\r\n" + "ffedbf 22\r\n" + "c 14\r\n"
				+ "ddcdce 9\r\n" + "cbecddc 9\r\n" + "af 6\r\n" + "f 11\r\n" + "ebaed 15\r\n" + "adabfcc 0\r\n"
				+ "bdfe 10\r\n" + "cdcadf 2\r\n" + "fbbfd 1\r\n" + "fbfad 16\r\n" + "de 24\r\n" + "fdadfa 2\r\n"
				+ "ea 3\r\n" + "abf 1\r\n" + "cceccea 10\r\n" + "ead 7\r\n" + "adabaa 0\r\n" + "dabcecb 15\r\n"
				+ "ecee 14\r\n" + "cbfabcc 13\r\n" + "fbc 11\r\n" + "cc 9\r\n" + "bfebad 0\r\n" + "feebeac 2\r\n"
				+ "bebcf 9\r\n" + "fcdbddb 22\r\n" + "d 23\r\n" + "e 23\r\n" + "edcfa 18\r\n" + "cbfed 13\r\n"
				+ "adaae 19\r\n" + "ceacfe 12\r\n" + "d 22\r\n" + "fdfdddd 19\r\n" + "bafbeaf 10\r\n" + "fcfbab 15\r\n"
				+ "fffefc 5\r\n" + "f 21\r\n" + "cffcfcd 17\r\n" + "aafdac 8\r\n" + "cacfdbd 19\r\n" + "cabcaec 19\r\n"
				+ "fffb 12\r\n" + "bfbbaa 20\r\n" + "ebbfac 16\r\n" + "cf 3\r\n" + "aeed 17\r\n" + "dff 20\r\n"
				+ "eadd 21\r\n" + "ccdbbcf 13\r\n" + "a 17\r\n" + "acbea 1\r\n" + "cddbaf 21\r\n" + "dcfe 19\r\n"
				+ "a 21\r\n" + "cbfefcf 12\r\n" + "ebba 3\r\n" + "cadcdc 0\r\n" + "dbb 21\r\n" + "bfc 13\r\n"
				+ "fbd 24\r\n" + "c 3\r\n" + "db 15\r\n" + "fbeadb 1\r\n" + "adc 20\r\n" + "dccddad 10\r\n" + "d 14\r\n"
				+ "dcefb 12\r\n" + "aac 23\r\n" + "aefceeb 24\r\n" + "ddcdaf 16\r\n" + "e 9\r\n" + "edbdfb 9\r\n"
				+ "bf 8\r\n" + "baeaed 9\r\n" + "acfb 22\r\n" + "d 12\r\n" + "cefddc 19\r\n" + "aded 2\r\n"
				+ "edcecfc 18\r\n" + "ce 9\r\n" + "a 12\r\n" + "abc 0\r\n" + "aae 13\r\n" + "fbbdafe 16\r\n"
				+ "aec 24\r\n" + "e 1\r\n" + "df 7\r\n" + "edabfe 12\r\n" + "bfbbecf 5\r\n" + "defbad 14\r\n"
				+ "a 9\r\n" + "aa 13\r\n" + "ba 18\r\n" + "fdb 17\r\n" + "adfdcb 22\r\n" + "ff 23\r\n"
				+ "cadddbb 17\r\n" + "bdc 0\r\n" + "ffdd 20\r\n" + "b 24\r\n" + "beb 3\r\n" + "efcbd 6\r\n"
				+ "bfbdac 7\r\n" + "edfc 21\r\n" + "accbb 19\r\n" + "adefaa 18\r\n" + "da 8\r\n" + "fbbfabd 22\r\n"
				+ "dbe 21\r\n" + "ac 1\r\n" + "fecdb 18\r\n" + "fe 12\r\n" + "cfc 17\r\n" + "fcaa 18\r\n" + "ecd 6\r\n"
				+ "bc 15\r\n" + "fafd 17\r\n" + "ced 2\r\n" + "e 19\r\n" + "aba 24\r\n" + "a 19\r\n" + "c 9\r\n"
				+ "aceceff 12\r\n" + "cbbdd 21\r\n" + "cdf 9\r\n" + "ffbed 7\r\n" + "adcaf 16\r\n" + "befba 16\r\n"
				+ "bddedff 0\r\n" + "aaf 2\r\n" + "bfb 19\r\n" + "efabda 15\r\n" + "bd 16\r\n" + "cbffdf 21\r\n"
				+ "dd 9\r\n" + "aecea 1\r\n" + "ced 9\r\n" + "daf 20\r\n" + "efb 24\r\n" + "aebd 23\r\n"
				+ "acaaba 4\r\n" + "fbbdfec 17\r\n" + "fddb 24\r\n" + "fb 9\r\n" + "c 6\r\n" + "f 14\r\n" + "def 4\r\n"
				+ "e 17\r\n" + "fdfbda 24\r\n" + "da 22\r\n" + "dffab 22\r\n" + "ffebc 23\r\n" + "ebdaebc 15\r\n"
				+ "fbeadc 16\r\n" + "fcaddf 24\r\n" + "cba 1\r\n" + "bb 5\r\n" + "ffbbb 8\r\n" + "aafda 11\r\n"
				+ "abedccf 1\r\n" + "abb 13\r\n" + "cea 24\r\n" + "c 24\r\n" + "eafcea 10\r\n" + "fabdce 3\r\n"
				+ "dc 11\r\n" + "bacce 19\r\n" + "bcdee 10\r\n" + "aebbaab 8\r\n" + "befcbf 11\r\n" + "fadb 11\r\n"
				+ "bfacbec 14\r\n" + "acef 17\r\n" + "f 22\r\n" + "d 6\r\n" + "cfb 5\r\n" + "fa 1\r\n" + "dc 10\r\n"
				+ "fc 23\r\n" + "dfafdff 22\r\n" + "cf 7\r\n" + "ff 14\r\n" + "ccea 12\r\n" + "da 7\r\n" + "ddb 3\r\n"
				+ "ecbb 23\r\n" + "bdabc 14\r\n" + "beebec 6\r\n" + "cd 17\r\n" + "ca 21\r\n" + "d 13\r\n"
				+ "faeff 24\r\n" + "dede 11\r\n" + "abee 5\r\n" + "bbef 10\r\n" + "ff 14\r\n" + "fce 0\r\n"
				+ "dcedac 13\r\n" + "fbced 23\r\n" + "efbdcdb 17\r\n" + "fadfeb 2\r\n" + "bcbbef 0\r\n" + "adbdf 11\r\n"
				+ "de 3\r\n" + "f 13\r\n" + "ffebf 22\r\n" + "debffbb 3\r\n" + "dde 6\r\n" + "bbeedfc 18\r\n"
				+ "faf 21\r\n" + "ccfdaaa 14\r\n" + "c 17\r\n" + "feab 24\r\n" + "bfae 13\r\n" + "fb 1\r\n"
				+ "efcb 19\r\n" + "e 4\r\n" + "d 20\r\n" + "fbbcebb 20\r\n" + "ceaf 12\r\n" + "cccfb 3\r\n"
				+ "aeec 3\r\n" + "fbaeaba 6\r\n" + "cbdc 3\r\n" + "fdab 17\r\n" + "effbd 21\r\n" + "f 1\r\n"
				+ "f 24\r\n" + "bbbceb 1\r\n" + "ccdccf 8\r\n" + "dae 8\r\n" + "fd 24\r\n" + "ceefddb 14\r\n"
				+ "bee 17\r\n" + "edfadea 10\r\n" + "a 2\r\n" + "dacfdf 7\r\n" + "ecdd 0\r\n" + "ebdfdcb 16\r\n"
				+ "cbd 3\r\n" + "becdd 12\r\n" + "aacae 6\r\n" + "ab 19\r\n" + "decead 15\r\n" + "fddde 23\r\n"
				+ "ea 19\r\n" + "cdbcd 21\r\n" + "ece 18\r\n" + "bcce 9\r\n" + "fb 11\r\n" + "c 4\r\n" + "ffb 10\r\n"
				+ "a 3\r\n" + "aacefea 23\r\n" + "edbf 10\r\n" + "c 7\r\n" + "dbbb 14\r\n" + "fdcb 17\r\n"
				+ "adacfa 1\r\n" + "ce 23\r\n" + "dffd 11\r\n" + "b 16\r\n" + "cabffeb 1\r\n" + "badb 11\r\n"
				+ "f 14\r\n" + "bf 16\r\n" + "c 9\r\n" + "fdebc 13\r\n" + "cda 1\r\n" + "baba 5\r\n" + "cdabaed 9\r\n"
				+ "cfa 21\r\n" + "bccdbda 4\r\n" + "aebedcd 12\r\n" + "babffc 18\r\n" + "cbcc 17\r\n" + "ce 4\r\n"
				+ "c 20\r\n" + "cfcde 8\r\n" + "ba 13\r\n" + "bfd 2\r\n" + "faef 19\r\n" + "dcf 18\r\n" + "d 7\r\n"
				+ "bcf 24\r\n" + "dcfca 14\r\n" + "bbef 19\r\n" + "ffd 17\r\n" + "eaa 24\r\n" + "bce 24\r\n"
				+ "dbaebfa 17\r\n" + "b 9\r\n" + "eec 9\r\n" + "bdcafa 21\r\n" + "f 20\r\n" + "ddbecbc 5\r\n"
				+ "cfbcec 11\r\n" + "eae 9\r\n" + "aeebdee 16\r\n" + "bbcfd 11\r\n" + "fdbccb 1\r\n" + "fcbf 7\r\n"
				+ "e 22\r\n" + "de 18\r\n" + "cd 2\r\n" + "ceaaffd 11\r\n" + "fd 8\r\n" + "aebf 23\r\n" + "caab 7\r\n"
				+ "b 1\r\n" + "ddcf 8\r\n" + "dfaafd 22\r\n" + "ccaeca 11\r\n" + "afa 5\r\n" + "ffbecc 17\r\n"
				+ "bbd 16\r\n" + "cebfebc 13\r\n" + "edde 0\r\n" + "fbbebca 14\r\n" + "ebdedce 5\r\n" + "dcefcb 12\r\n"
				+ "effaa 23\r\n" + "bacb 11\r\n" + "defeca 21\r\n" + "daaad 0\r\n" + "efbbda 0\r\n" + "cccafd 23\r\n"
				+ "ececdfd 0\r\n" + "bfacc 10\r\n" + "a 24\r\n" + "dabecd 0\r\n" + "abaffa 21\r\n" + "b 19\r\n"
				+ "bbcece 22\r\n" + "ddfde 11\r\n" + "cfaaf 20\r\n" + "fcadaf 14\r\n" + "aeacc 11\r\n" + "fd 10\r\n"
				+ "ab 1\r\n" + "eac 11\r\n" + "bafecf 14\r\n" + "dbf 11\r\n" + "adfa 12\r\n" + "efde 20\r\n"
				+ "cf 7\r\n" + "ffefec 15\r\n" + "eefde 17\r\n" + "cdea 6\r\n" + "cac 20\r\n" + "cbedb 23\r\n"
				+ "fa 21\r\n" + "eec 16\r\n" + "a 16\r\n" + "afe 22\r\n" + "fd 13\r\n" + "afecead 4\r\n" + "bffaf 5\r\n"
				+ "ff 6\r\n" + "cf 12\r\n" + "eacbcc 18\r\n" + "bcaf 4\r\n" + "fb 13\r\n" + "adfcaef 16\r\n" + "b 6\r\n"
				+ "efeb 23\r\n" + "deafe 1\r\n" + "e 9\r\n" + "fa 4\r\n" + "ca 17\r\n" + "facbf 7\r\n" + "cbfdf 14\r\n"
				+ "eedcd 1\r\n" + "e 13\r\n" + "fd 0\r\n" + "bbfab 15\r\n" + "ecaad 15\r\n" + "dacfcff 21\r\n"
				+ "ecfdf 23\r\n" + "eb 11\r\n" + "afafcd 5\r\n" + "eccbc 12\r\n" + "efecdcf 14\r\n" + "eebbdfc 17\r\n"
				+ "d 7\r\n" + "abbc 11\r\n" + "cdd 14\r\n" + "deceff 8\r\n" + "babcd 18\r\n" + "bc 19\r\n" + "fad 7\r\n"
				+ "eceff 15\r\n" + "abecede 12\r\n" + "e 14\r\n" + "cfebb 4\r\n" + "ee 8\r\n" + "fcfbb 17\r\n"
				+ "dbacdc 4\r\n" + "baea 21\r\n" + "def 23\r\n" + "cbfae 11\r\n" + "defacd 3\r\n" + "dcdac 6\r\n"
				+ "bcffebd 9\r\n" + "fcaeb 1\r\n" + "cacaddf 8\r\n" + "c 23\r\n" + "ebfd 21\r\n" + "dfe 13\r\n"
				+ "adb 0\r\n" + "adaaba 14\r\n" + "daad 23\r\n" + "bfdf 6\r\n" + "bdaf 0\r\n" + "edec 17\r\n"
				+ "daef 7\r\n" + "b 10\r\n" + "bee 15\r\n" + "dfdeae 14\r\n" + "cba 11\r\n" + "ea 22\r\n"
				+ "edcb 13\r\n" + "cdcc 19\r\n" + "edcbae 8\r\n" + "dd 14\r\n" + "dbaffbf 4\r\n" + "b 11\r\n"
				+ "bda 19\r\n" + "e 19\r\n" + "becaccd 22\r\n" + "e 1\r\n" + "fafcfee 0\r\n" + "eff 13\r\n"
				+ "beb 11\r\n" + "df 24\r\n" + "f 0\r\n" + "a 16\r\n" + "ae 14\r\n" + "ef 9\r\n" + "da 14\r\n"
				+ "fcbcbae 13\r\n" + "ffbacc 10\r\n" + "acde 13\r\n" + "ae 20\r\n" + "aadadd 5\r\n" + "cf 16\r\n"
				+ "bbbc 24\r\n" + "cbccd 5\r\n" + "affed 8\r\n" + "ccafda 20\r\n" + "dfa 19\r\n" + "afb 15\r\n"
				+ "cdcda 15\r\n" + "dcabbcb 13\r\n" + "acbcaef 7\r\n" + "cba 19\r\n" + "bac 11\r\n" + "cebef 8");

		case2.setOutput("a 24\r\n" + "a 24\r\n" + "aba 24\r\n" + "acea 24\r\n" + "adfd 24\r\n" + "aec 24\r\n"
				+ "aefceeb 24\r\n" + "b 24\r\n" + "bb 24\r\n" + "bbbc 24\r\n" + "bc 24\r\n" + "bce 24\r\n"
				+ "bcf 24\r\n" + "bd 24\r\n" + "be 24\r\n" + "becacdc 24\r\n" + "c 24\r\n" + "c 24\r\n" + "c 24\r\n"
				+ "c 24\r\n" + "cacbfac 24\r\n" + "cbbffa 24\r\n" + "ccfbad 24\r\n" + "cda 24\r\n" + "cea 24\r\n"
				+ "cf 24\r\n" + "dab 24\r\n" + "dc 24\r\n" + "dd 24\r\n" + "de 24\r\n" + "de 24\r\n" + "deac 24\r\n"
				+ "dedbaae 24\r\n" + "df 24\r\n" + "dfdad 24\r\n" + "dfebc 24\r\n" + "e 24\r\n" + "eaa 24\r\n"
				+ "ebaabdc 24\r\n" + "efaeba 24\r\n" + "efb 24\r\n" + "f 24\r\n" + "faeff 24\r\n" + "fbd 24\r\n"
				+ "fcaddf 24\r\n" + "fd 24\r\n" + "fddb 24\r\n" + "fdf 24\r\n" + "fdfbda 24\r\n" + "feab 24\r\n"
				+ "a 23\r\n" + "aac 23\r\n" + "aacefea 23\r\n" + "adb 23\r\n" + "add 23\r\n" + "ae 23\r\n"
				+ "aebd 23\r\n" + "aebf 23\r\n" + "bdfefa 23\r\n" + "bfc 23\r\n" + "bfedaad 23\r\n" + "c 23\r\n"
				+ "c 23\r\n" + "cbedb 23\r\n" + "cccafd 23\r\n" + "cd 23\r\n" + "ce 23\r\n" + "cf 23\r\n" + "cfa 23\r\n"
				+ "d 23\r\n" + "d 23\r\n" + "daad 23\r\n" + "def 23\r\n" + "dffbbb 23\r\n" + "e 23\r\n" + "e 23\r\n"
				+ "e 23\r\n" + "eacd 23\r\n" + "ecbb 23\r\n" + "ecfdf 23\r\n" + "efcbfd 23\r\n" + "efeb 23\r\n"
				+ "effaa 23\r\n" + "fbbaefc 23\r\n" + "fbced 23\r\n" + "fc 23\r\n" + "fdccfd 23\r\n" + "fddde 23\r\n"
				+ "feecebb 23\r\n" + "ff 23\r\n" + "ffebc 23\r\n" + "fffa 23\r\n" + "a 22\r\n" + "a 22\r\n"
				+ "aafcecc 22\r\n" + "ab 22\r\n" + "abdbf 22\r\n" + "abeeb 22\r\n" + "acb 22\r\n" + "acfb 22\r\n"
				+ "adfdcb 22\r\n" + "aedb 22\r\n" + "afe 22\r\n" + "b 22\r\n" + "bb 22\r\n" + "bbbd 22\r\n"
				+ "bbcece 22\r\n" + "bddaf 22\r\n" + "bdeb 22\r\n" + "be 22\r\n" + "becaccd 22\r\n" + "cbaf 22\r\n"
				+ "cbf 22\r\n" + "cbfbfdd 22\r\n" + "d 22\r\n" + "da 22\r\n" + "dbcccca 22\r\n" + "dfaafd 22\r\n"
				+ "dfafdff 22\r\n" + "dfcedd 22\r\n" + "dffab 22\r\n" + "e 22\r\n" + "ea 22\r\n" + "eacfc 22\r\n"
				+ "ed 22\r\n" + "eddfabf 22\r\n" + "f 22\r\n" + "f 22\r\n" + "fa 22\r\n" + "fba 22\r\n"
				+ "fbbeedd 22\r\n" + "fbbfabd 22\r\n" + "fcdbddb 22\r\n" + "fcfabfc 22\r\n" + "ffebf 22\r\n"
				+ "ffedbf 22\r\n" + "a 21\r\n" + "a 21\r\n" + "aacca 21\r\n" + "abaffa 21\r\n" + "adba 21\r\n"
				+ "aea 21\r\n" + "aedc 21\r\n" + "baea 21\r\n" + "bbea 21\r\n" + "bcdfd 21\r\n" + "bdcafa 21\r\n"
				+ "ca 21\r\n" + "cbbdd 21\r\n" + "cbffdf 21\r\n" + "cdbcd 21\r\n" + "cddbaf 21\r\n" + "cdfaa 21\r\n"
				+ "cea 21\r\n" + "ced 21\r\n" + "cfa 21\r\n" + "dacfcff 21\r\n" + "dbb 21\r\n" + "dbe 21\r\n"
				+ "dcab 21\r\n" + "deefec 21\r\n" + "defeca 21\r\n" + "dfcdbef 21\r\n" + "e 21\r\n" + "e 21\r\n"
				+ "eacfef 21\r\n" + "ead 21\r\n" + "eadd 21\r\n" + "ebfd 21\r\n" + "edaed 21\r\n" + "eddcbee 21\r\n"
				+ "edfc 21\r\n" + "efadd 21\r\n" + "effbd 21\r\n" + "f 21\r\n" + "fa 21\r\n" + "fa 21\r\n"
				+ "fae 21\r\n" + "faf 21\r\n" + "fcb 21\r\n" + "febf 21\r\n" + "fffefbd 21\r\n" + "ac 20\r\n"
				+ "acabbd 20\r\n" + "adaf 20\r\n" + "adc 20\r\n" + "ae 20\r\n" + "aec 20\r\n" + "aecc 20\r\n"
				+ "afcd 20\r\n" + "bbbacae 20\r\n" + "bea 20\r\n" + "becac 20\r\n" + "bfbbaa 20\r\n" + "c 20\r\n"
				+ "cac 20\r\n" + "caddba 20\r\n" + "ccafda 20\r\n" + "cdcacbd 20\r\n" + "cecddf 20\r\n"
				+ "ceefdd 20\r\n" + "cfaaf 20\r\n" + "cfbbeb 20\r\n" + "d 20\r\n" + "d 20\r\n" + "dacb 20\r\n"
				+ "daf 20\r\n" + "daffb 20\r\n" + "dba 20\r\n" + "dbca 20\r\n" + "dcdffaa 20\r\n" + "ddbcb 20\r\n"
				+ "ddc 20\r\n" + "dfccee 20\r\n" + "dff 20\r\n" + "eace 20\r\n" + "eb 20\r\n" + "ecc 20\r\n"
				+ "ed 20\r\n" + "eeba 20\r\n" + "eecaa 20\r\n" + "efde 20\r\n" + "f 20\r\n" + "fbbcebb 20\r\n"
				+ "ffdd 20\r\n" + "a 19\r\n" + "ab 19\r\n" + "abdccc 19\r\n" + "accbb 19\r\n" + "adaae 19\r\n"
				+ "adeccbe 19\r\n" + "ae 19\r\n" + "aedc 19\r\n" + "aeeef 19\r\n" + "afd 19\r\n" + "b 19\r\n"
				+ "bacce 19\r\n" + "bbef 19\r\n" + "bc 19\r\n" + "bda 19\r\n" + "bfb 19\r\n" + "bfc 19\r\n"
				+ "cabcaec 19\r\n" + "cacfdbd 19\r\n" + "caf 19\r\n" + "cba 19\r\n" + "cd 19\r\n" + "cdcc 19\r\n"
				+ "cea 19\r\n" + "cefddc 19\r\n" + "dacecc 19\r\n" + "daf 19\r\n" + "dcfe 19\r\n" + "de 19\r\n"
				+ "dfa 19\r\n" + "e 19\r\n" + "e 19\r\n" + "ea 19\r\n" + "ebdfddd 19\r\n" + "ecb 19\r\n" + "efcb 19\r\n"
				+ "efdc 19\r\n" + "faef 19\r\n" + "fdfdddd 19\r\n" + "ffbce 19\r\n" + "fffdfce 19\r\n" + "abbdde 18\r\n"
				+ "ad 18\r\n" + "adeafb 18\r\n" + "adefaa 18\r\n" + "aebeefd 18\r\n" + "afbcb 18\r\n" + "b 18\r\n"
				+ "b 18\r\n" + "ba 18\r\n" + "babcd 18\r\n" + "babffc 18\r\n" + "bb 18\r\n" + "bbeedfc 18\r\n"
				+ "cddfd 18\r\n" + "ceb 18\r\n" + "daddac 18\r\n" + "dbf 18\r\n" + "dcf 18\r\n" + "dcf 18\r\n"
				+ "dda 18\r\n" + "de 18\r\n" + "dfaaccb 18\r\n" + "eacbcc 18\r\n" + "ebdeae 18\r\n" + "ecd 18\r\n"
				+ "ece 18\r\n" + "edcecfc 18\r\n" + "edcfa 18\r\n" + "efdfdfd 18\r\n" + "effca 18\r\n" + "fcaa 18\r\n"
				+ "fcfccda 18\r\n" + "fd 18\r\n" + "fdacdff 18\r\n" + "fecdb 18\r\n" + "ffbfca 18\r\n" + "a 17\r\n"
				+ "a 17\r\n" + "aaceb 17\r\n" + "abca 17\r\n" + "acef 17\r\n" + "adbcf 17\r\n" + "aeed 17\r\n"
				+ "afad 17\r\n" + "b 17\r\n" + "b 17\r\n" + "bbcf 17\r\n" + "bee 17\r\n" + "beeac 17\r\n"
				+ "bfacbc 17\r\n" + "c 17\r\n" + "ca 17\r\n" + "cadddbb 17\r\n" + "cbcc 17\r\n" + "ccecfcb 17\r\n"
				+ "cd 17\r\n" + "ceddf 17\r\n" + "cfc 17\r\n" + "cffcfcd 17\r\n" + "dafcecb 17\r\n" + "dbaebfa 17\r\n"
				+ "dec 17\r\n" + "deebdee 17\r\n" + "e 17\r\n" + "ed 17\r\n" + "edec 17\r\n" + "ededdc 17\r\n"
				+ "eebbdfc 17\r\n" + "eefde 17\r\n" + "efbdcdb 17\r\n" + "efbea 17\r\n" + "f 17\r\n" + "f 17\r\n"
				+ "fafd 17\r\n" + "fbbdfec 17\r\n" + "fcfbb 17\r\n" + "fdab 17\r\n" + "fdb 17\r\n" + "fdcb 17\r\n"
				+ "fedbccf 17\r\n" + "fede 17\r\n" + "ffbecc 17\r\n" + "ffd 17\r\n" + "a 16\r\n" + "a 16\r\n"
				+ "a 16\r\n" + "adcaf 16\r\n" + "adfcaef 16\r\n" + "aeebdee 16\r\n" + "b 16\r\n" + "ba 16\r\n"
				+ "bbd 16\r\n" + "bd 16\r\n" + "bebda 16\r\n" + "befba 16\r\n" + "bf 16\r\n" + "bfbffcf 16\r\n"
				+ "cc 16\r\n" + "cf 16\r\n" + "d 16\r\n" + "da 16\r\n" + "dda 16\r\n" + "ddcdaf 16\r\n" + "df 16\r\n"
				+ "dfdcdf 16\r\n" + "ebbfac 16\r\n" + "ebdfdcb 16\r\n" + "edbb 16\r\n" + "edddfcf 16\r\n" + "edf 16\r\n"
				+ "eec 16\r\n" + "f 16\r\n" + "f 16\r\n" + "faf 16\r\n" + "fbbdafe 16\r\n" + "fbeadc 16\r\n"
				+ "fbfad 16\r\n" + "fce 16\r\n" + "ffde 16\r\n" + "aaacb 15\r\n" + "ab 15\r\n" + "acdaac 15\r\n"
				+ "adfa 15\r\n" + "aea 15\r\n" + "aeacad 15\r\n" + "afb 15\r\n" + "b 15\r\n" + "b 15\r\n"
				+ "baebbed 15\r\n" + "bbeabfb 15\r\n" + "bbfab 15\r\n" + "bc 15\r\n" + "bc 15\r\n" + "bee 15\r\n"
				+ "c 15\r\n" + "c 15\r\n" + "cbfebc 15\r\n" + "cdcda 15\r\n" + "dabcecb 15\r\n" + "dadebdb 15\r\n"
				+ "db 15\r\n" + "dbdfeb 15\r\n" + "dcb 15\r\n" + "ddfcbac 15\r\n" + "decead 15\r\n" + "ebaed 15\r\n"
				+ "ebdaebc 15\r\n" + "ecaad 15\r\n" + "eceff 15\r\n" + "efabda 15\r\n" + "efe 15\r\n" + "efffbc 15\r\n"
				+ "f 15\r\n" + "f 15\r\n" + "fcfbab 15\r\n" + "fd 15\r\n" + "fe 15\r\n" + "fec 15\r\n" + "ff 15\r\n"
				+ "ff 15\r\n" + "ffefec 15\r\n" + "aaefacb 14\r\n" + "ab 14\r\n" + "abcae 14\r\n" + "adaaba 14\r\n"
				+ "ae 14\r\n" + "aebcdbd 14\r\n" + "aeecfee 14\r\n" + "badc 14\r\n" + "bafecf 14\r\n" + "bc 14\r\n"
				+ "bc 14\r\n" + "bdabc 14\r\n" + "bfacbec 14\r\n" + "c 14\r\n" + "ca 14\r\n" + "cbfa 14\r\n"
				+ "cbfdf 14\r\n" + "ccfdaaa 14\r\n" + "cd 14\r\n" + "cdd 14\r\n" + "ceefddb 14\r\n" + "cfdcabb 14\r\n"
				+ "d 14\r\n" + "d 14\r\n" + "d 14\r\n" + "da 14\r\n" + "dadfedb 14\r\n" + "daec 14\r\n" + "dbbb 14\r\n"
				+ "dbe 14\r\n" + "dcfca 14\r\n" + "dd 14\r\n" + "ddd 14\r\n" + "ddd 14\r\n" + "defbad 14\r\n"
				+ "dfdeae 14\r\n" + "e 14\r\n" + "ecee 14\r\n" + "eea 14\r\n" + "eee 14\r\n" + "eefc 14\r\n"
				+ "efecdcf 14\r\n" + "f 14\r\n" + "f 14\r\n" + "fadeb 14\r\n" + "faefade 14\r\n" + "fbbebca 14\r\n"
				+ "fbedfba 14\r\n" + "fcadaf 14\r\n" + "fefac 14\r\n" + "ff 14\r\n" + "ff 14\r\n" + "ffe 14\r\n"
				+ "aa 13\r\n" + "aae 13\r\n" + "abb 13\r\n" + "acde 13\r\n" + "ad 13\r\n" + "afbc 13\r\n" + "ba 13\r\n"
				+ "bae 13\r\n" + "bc 13\r\n" + "bfae 13\r\n" + "bfc 13\r\n" + "c 13\r\n" + "c 13\r\n" + "cac 13\r\n"
				+ "cbbba 13\r\n" + "cbed 13\r\n" + "cbfabcc 13\r\n" + "cbfed 13\r\n" + "cc 13\r\n" + "ccdbbcf 13\r\n"
				+ "cebfebc 13\r\n" + "d 13\r\n" + "d 13\r\n" + "dbffbdc 13\r\n" + "dcabbcb 13\r\n" + "dccb 13\r\n"
				+ "dcedac 13\r\n" + "dfcf 13\r\n" + "dfe 13\r\n" + "e 13\r\n" + "ebbea 13\r\n" + "edcb 13\r\n"
				+ "eff 13\r\n" + "f 13\r\n" + "fab 13\r\n" + "fadfc 13\r\n" + "fb 13\r\n" + "fcbcbae 13\r\n"
				+ "fd 13\r\n" + "fdebc 13\r\n" + "feadbe 13\r\n" + "fefeeed 13\r\n" + "ffcdff 13\r\n" + "a 12\r\n"
				+ "aabcb 12\r\n" + "aafde 12\r\n" + "abecede 12\r\n" + "aceceff 12\r\n" + "aced 12\r\n" + "adfa 12\r\n"
				+ "aebedcd 12\r\n" + "afd 12\r\n" + "bcd 12\r\n" + "bdcbfcc 12\r\n" + "becdd 12\r\n" + "bfbe 12\r\n"
				+ "cbcb 12\r\n" + "cbfefcf 12\r\n" + "ccc 12\r\n" + "ccea 12\r\n" + "cd 12\r\n" + "ceacfe 12\r\n"
				+ "ceaf 12\r\n" + "cebfa 12\r\n" + "cec 12\r\n" + "cecd 12\r\n" + "cef 12\r\n" + "cf 12\r\n"
				+ "d 12\r\n" + "d 12\r\n" + "dabfac 12\r\n" + "dae 12\r\n" + "dca 12\r\n" + "dcefb 12\r\n"
				+ "dcefcb 12\r\n" + "dcfcfbb 12\r\n" + "e 12\r\n" + "eacf 12\r\n" + "eafab 12\r\n" + "eccbc 12\r\n"
				+ "edabfe 12\r\n" + "eee 12\r\n" + "fe 12\r\n" + "fffb 12\r\n" + "aafda 11\r\n" + "abbc 11\r\n"
				+ "abbc 11\r\n" + "adbdf 11\r\n" + "adbedfe 11\r\n" + "aeacc 11\r\n" + "b 11\r\n" + "bac 11\r\n"
				+ "bacb 11\r\n" + "badb 11\r\n" + "bbcfd 11\r\n" + "beadfe 11\r\n" + "beb 11\r\n" + "befcbf 11\r\n"
				+ "ca 11\r\n" + "cba 11\r\n" + "cbfae 11\r\n" + "ccaeca 11\r\n" + "cccdaf 11\r\n" + "cceec 11\r\n"
				+ "ce 11\r\n" + "ceaaffd 11\r\n" + "cebdae 11\r\n" + "cfaffff 11\r\n" + "cfbcec 11\r\n" + "dbdde 11\r\n"
				+ "dbf 11\r\n" + "dc 11\r\n" + "ddfbb 11\r\n" + "ddfde 11\r\n" + "dede 11\r\n" + "df 11\r\n"
				+ "dffd 11\r\n" + "e 11\r\n" + "e 11\r\n" + "eac 11\r\n" + "eb 11\r\n" + "efcfb 11\r\n" + "f 11\r\n"
				+ "fadb 11\r\n" + "fb 11\r\n" + "fbc 11\r\n" + "fbfeecf 11\r\n" + "fca 11\r\n" + "feb 11\r\n"
				+ "ffacad 11\r\n" + "ffccff 11\r\n" + "a 10\r\n" + "aadaafb 10\r\n" + "ac 10\r\n" + "adfebd 10\r\n"
				+ "ae 10\r\n" + "b 10\r\n" + "bafbeaf 10\r\n" + "bafdaa 10\r\n" + "bbef 10\r\n" + "bcadedd 10\r\n"
				+ "bcdee 10\r\n" + "bdfe 10\r\n" + "bfacc 10\r\n" + "bff 10\r\n" + "c 10\r\n" + "cceccea 10\r\n"
				+ "cdfbbdf 10\r\n" + "cebebb 10\r\n" + "ceddff 10\r\n" + "d 10\r\n" + "dc 10\r\n" + "dccddad 10\r\n"
				+ "eacb 10\r\n" + "eafcea 10\r\n" + "ebcecb 10\r\n" + "edbf 10\r\n" + "edfadea 10\r\n" + "f 10\r\n"
				+ "fbabed 10\r\n" + "fcb 10\r\n" + "fd 10\r\n" + "ffb 10\r\n" + "ffbacc 10\r\n" + "a 9\r\n"
				+ "acbebf 9\r\n" + "aedb 9\r\n" + "aeddf 9\r\n" + "afdb 9\r\n" + "b 9\r\n" + "baeaec 9\r\n"
				+ "baeaed 9\r\n" + "bccdf 9\r\n" + "bcce 9\r\n" + "bcffebd 9\r\n" + "bea 9\r\n" + "bebcf 9\r\n"
				+ "bedaefd 9\r\n" + "bfdbe 9\r\n" + "bfeeeeb 9\r\n" + "c 9\r\n" + "c 9\r\n" + "cbecddc 9\r\n"
				+ "cc 9\r\n" + "cc 9\r\n" + "cc 9\r\n" + "ccdd 9\r\n" + "ccef 9\r\n" + "cdabaed 9\r\n" + "cdeaa 9\r\n"
				+ "cdf 9\r\n" + "ce 9\r\n" + "ced 9\r\n" + "cfdb 9\r\n" + "d 9\r\n" + "dd 9\r\n" + "ddc 9\r\n"
				+ "ddcdce 9\r\n" + "e 9\r\n" + "e 9\r\n" + "e 9\r\n" + "eae 9\r\n" + "edbdfb 9\r\n" + "eeab 9\r\n"
				+ "eec 9\r\n" + "ef 9\r\n" + "efc 9\r\n" + "facab 9\r\n" + "fb 9\r\n" + "fbbcba 9\r\n" + "fbbfceb 9\r\n"
				+ "fbcab 9\r\n" + "ffea 9\r\n" + "a 8\r\n" + "aaaccce 8\r\n" + "aafdac 8\r\n" + "ac 8\r\n"
				+ "aebbaab 8\r\n" + "afc 8\r\n" + "affed 8\r\n" + "bcfb 8\r\n" + "beebb 8\r\n" + "bf 8\r\n"
				+ "cacaddf 8\r\n" + "ccdccf 8\r\n" + "cebeabb 8\r\n" + "cebef 8\r\n" + "cfcde 8\r\n" + "da 8\r\n"
				+ "da 8\r\n" + "dae 8\r\n" + "dbaa 8\r\n" + "dbcabd 8\r\n" + "dd 8\r\n" + "ddcf 8\r\n" + "deceff 8\r\n"
				+ "dfadadf 8\r\n" + "ed 8\r\n" + "edcbae 8\r\n" + "ee 8\r\n" + "eebeeee 8\r\n" + "fb 8\r\n" + "fd 8\r\n"
				+ "fddaaf 8\r\n" + "ffbbb 8\r\n" + "ffbbeb 8\r\n" + "ffdf 8\r\n" + "ab 7\r\n" + "acbcaef 7\r\n"
				+ "adce 7\r\n" + "af 7\r\n" + "bbddae 7\r\n" + "becf 7\r\n" + "bfbdac 7\r\n" + "bfbdfe 7\r\n"
				+ "bfcdcca 7\r\n" + "c 7\r\n" + "caab 7\r\n" + "cccffae 7\r\n" + "cefebdc 7\r\n" + "cf 7\r\n"
				+ "cf 7\r\n" + "cfbbfd 7\r\n" + "d 7\r\n" + "d 7\r\n" + "d 7\r\n" + "da 7\r\n" + "dacfdf 7\r\n"
				+ "daef 7\r\n" + "dcaaa 7\r\n" + "dcc 7\r\n" + "dcedc 7\r\n" + "df 7\r\n" + "e 7\r\n" + "e 7\r\n"
				+ "ead 7\r\n" + "ecbbf 7\r\n" + "edabc 7\r\n" + "efce 7\r\n" + "eff 7\r\n" + "f 7\r\n" + "facbf 7\r\n"
				+ "fad 7\r\n" + "fcb 7\r\n" + "fcbf 7\r\n" + "fdcfafc 7\r\n" + "ffbed 7\r\n" + "aacae 6\r\n"
				+ "acadaea 6\r\n" + "aeada 6\r\n" + "af 6\r\n" + "b 6\r\n" + "b 6\r\n" + "baacefb 6\r\n" + "bee 6\r\n"
				+ "beeabe 6\r\n" + "beebec 6\r\n" + "bfdf 6\r\n" + "c 6\r\n" + "cabaac 6\r\n" + "caedfcf 6\r\n"
				+ "cdea 6\r\n" + "cecfda 6\r\n" + "cee 6\r\n" + "cf 6\r\n" + "cfcee 6\r\n" + "d 6\r\n" + "dacbfdf 6\r\n"
				+ "dcdac 6\r\n" + "dda 6\r\n" + "dde 6\r\n" + "ddecede 6\r\n" + "eccdcfa 6\r\n" + "ecd 6\r\n"
				+ "efaaadf 6\r\n" + "efafbfc 6\r\n" + "efcbd 6\r\n" + "efe 6\r\n" + "f 6\r\n" + "f 6\r\n"
				+ "fbaeaba 6\r\n" + "fdbd 6\r\n" + "ff 6\r\n" + "ff 6\r\n" + "ffc 6\r\n" + "aa 5\r\n" + "aadadd 5\r\n"
				+ "abee 5\r\n" + "acbb 5\r\n" + "acfdf 5\r\n" + "aefbdc 5\r\n" + "afa 5\r\n" + "afafcd 5\r\n"
				+ "baba 5\r\n" + "bb 5\r\n" + "bcbef 5\r\n" + "bcd 5\r\n" + "bd 5\r\n" + "bfbbecf 5\r\n" + "bffaf 5\r\n"
				+ "c 5\r\n" + "cbbeea 5\r\n" + "cbccd 5\r\n" + "cfb 5\r\n" + "d 5\r\n" + "daf 5\r\n" + "ddbecbc 5\r\n"
				+ "e 5\r\n" + "eafcecb 5\r\n" + "ebdedce 5\r\n" + "eef 5\r\n" + "fbecce 5\r\n" + "fffefc 5\r\n"
				+ "aa 4\r\n" + "aaafc 4\r\n" + "acaaba 4\r\n" + "afecead 4\r\n" + "bcaf 4\r\n" + "bccdbda 4\r\n"
				+ "bebfbdb 4\r\n" + "bf 4\r\n" + "c 4\r\n" + "c 4\r\n" + "cafcb 4\r\n" + "cca 4\r\n" + "ce 4\r\n"
				+ "cf 4\r\n" + "cfcabcf 4\r\n" + "cfebb 4\r\n" + "cfedcac 4\r\n" + "dbacdc 4\r\n" + "dbaffbf 4\r\n"
				+ "dbecda 4\r\n" + "dcceaa 4\r\n" + "ddffceb 4\r\n" + "def 4\r\n" + "e 4\r\n" + "e 4\r\n"
				+ "eeaddce 4\r\n" + "fa 4\r\n" + "fe 4\r\n" + "a 3\r\n" + "a 3\r\n" + "aeec 3\r\n" + "baaba 3\r\n"
				+ "bd 3\r\n" + "beb 3\r\n" + "bffb 3\r\n" + "c 3\r\n" + "cbd 3\r\n" + "cbdc 3\r\n" + "cccfb 3\r\n"
				+ "cdefdf 3\r\n" + "ceacfbb 3\r\n" + "cf 3\r\n" + "ddb 3\r\n" + "de 3\r\n" + "debffbb 3\r\n"
				+ "defacd 3\r\n" + "ea 3\r\n" + "ebba 3\r\n" + "edcccf 3\r\n" + "edcfd 3\r\n" + "eec 3\r\n"
				+ "efdabfd 3\r\n" + "f 3\r\n" + "fabdce 3\r\n" + "ff 3\r\n" + "a 2\r\n" + "aaf 2\r\n" + "aded 2\r\n"
				+ "aed 2\r\n" + "afdeabf 2\r\n" + "b 2\r\n" + "bdbe 2\r\n" + "bfd 2\r\n" + "bfe 2\r\n" + "c 2\r\n"
				+ "cacaaa 2\r\n" + "cd 2\r\n" + "cdcadf 2\r\n" + "ced 2\r\n" + "d 2\r\n" + "dc 2\r\n" + "dddaab 2\r\n"
				+ "dfebefa 2\r\n" + "e 2\r\n" + "ecb 2\r\n" + "fa 2\r\n" + "fadfeb 2\r\n" + "fdadfa 2\r\n"
				+ "feebeac 2\r\n" + "ffdbd 2\r\n" + "ab 1\r\n" + "abaf 1\r\n" + "abcddc 1\r\n" + "abedccf 1\r\n"
				+ "abf 1\r\n" + "abfaacb 1\r\n" + "ac 1\r\n" + "acbea 1\r\n" + "acdeafb 1\r\n" + "adacfa 1\r\n"
				+ "aecea 1\r\n" + "aed 1\r\n" + "aeedcca 1\r\n" + "b 1\r\n" + "bb 1\r\n" + "bbbceb 1\r\n" + "c 1\r\n"
				+ "cabffeb 1\r\n" + "cba 1\r\n" + "cda 1\r\n" + "cffafcd 1\r\n" + "d 1\r\n" + "dbd 1\r\n"
				+ "dbedcaf 1\r\n" + "deafe 1\r\n" + "e 1\r\n" + "e 1\r\n" + "e 1\r\n" + "eaabea 1\r\n" + "eabaad 1\r\n"
				+ "ebbfcbe 1\r\n" + "eecaba 1\r\n" + "eedcd 1\r\n" + "efacd 1\r\n" + "f 1\r\n" + "fa 1\r\n" + "fb 1\r\n"
				+ "fbbfd 1\r\n" + "fbeadb 1\r\n" + "fc 1\r\n" + "fcaeb 1\r\n" + "fdbccb 1\r\n" + "fea 1\r\n"
				+ "aafddb 0\r\n" + "abc 0\r\n" + "adabaa 0\r\n" + "adabfcc 0\r\n" + "adb 0\r\n" + "afafadd 0\r\n"
				+ "bcbbef 0\r\n" + "bcceffc 0\r\n" + "bdaf 0\r\n" + "bdc 0\r\n" + "bddedff 0\r\n" + "bfebad 0\r\n"
				+ "c 0\r\n" + "cadcdc 0\r\n" + "cafdbf 0\r\n" + "ccabeb 0\r\n" + "ccf 0\r\n" + "cddaca 0\r\n"
				+ "ce 0\r\n" + "daaad 0\r\n" + "dabecd 0\r\n" + "dbcae 0\r\n" + "dcbedb 0\r\n" + "e 0\r\n" + "eac 0\r\n"
				+ "eb 0\r\n" + "ebc 0\r\n" + "ebcd 0\r\n" + "ebcffe 0\r\n" + "ecdd 0\r\n" + "ececdfd 0\r\n"
				+ "edd 0\r\n" + "edde 0\r\n" + "efbbda 0\r\n" + "f 0\r\n" + "f 0\r\n" + "fafcfee 0\r\n" + "fce 0\r\n"
				+ "fd 0\r\n" + "fdacfbc 0\r\n" + "fde 0\r\n" + "fefdaa 0\r\n" + "ff 0\r\n" + "fffad 0");

		case3.setInput("1000\r\n" + "adbab 17\r\n" + "cd 16\r\n" + "aaaa 0\r\n" + "b 0\r\n" + "ccaa 6\r\n" + "ab 0\r\n"
				+ "accb 12\r\n" + "aabdd 18\r\n" + "dddb 3\r\n" + "ca 21\r\n" + "bd 7\r\n" + "ddbcd 10\r\n"
				+ "ab 10\r\n" + "cadb 16\r\n" + "accb 0\r\n" + "dabdb 5\r\n" + "baacd 6\r\n" + "d 9\r\n" + "dd 11\r\n"
				+ "ccdb 7\r\n" + "dabb 12\r\n" + "dd 21\r\n" + "baabd 22\r\n" + "bdaac 22\r\n" + "bcaa 13\r\n"
				+ "cca 11\r\n" + "abdd 18\r\n" + "ab 7\r\n" + "addb 24\r\n" + "cadab 20\r\n" + "cba 10\r\n"
				+ "adaab 11\r\n" + "cca 19\r\n" + "caabb 2\r\n" + "dc 20\r\n" + "acac 2\r\n" + "cda 24\r\n" + "a 21\r\n"
				+ "da 3\r\n" + "acba 3\r\n" + "b 8\r\n" + "bddad 13\r\n" + "b 17\r\n" + "daabd 18\r\n" + "ca 5\r\n"
				+ "daab 2\r\n" + "db 4\r\n" + "cd 17\r\n" + "d 7\r\n" + "a 0\r\n" + "ada 20\r\n" + "baa 4\r\n"
				+ "daad 11\r\n" + "c 9\r\n" + "cdac 0\r\n" + "b 9\r\n" + "bcdb 22\r\n" + "caad 14\r\n" + "ddc 12\r\n"
				+ "da 2\r\n" + "caad 6\r\n" + "cd 0\r\n" + "ada 10\r\n" + "aaaad 3\r\n" + "daadd 23\r\n"
				+ "bacba 14\r\n" + "bdc 16\r\n" + "cabab 23\r\n" + "bc 21\r\n" + "ad 4\r\n" + "c 12\r\n" + "cdda 9\r\n"
				+ "b 3\r\n" + "ab 20\r\n" + "acd 0\r\n" + "abb 13\r\n" + "d 19\r\n" + "ccabc 18\r\n" + "bcbb 8\r\n"
				+ "b 16\r\n" + "dbcc 21\r\n" + "baac 3\r\n" + "cbdaa 22\r\n" + "cb 10\r\n" + "dd 24\r\n" + "dc 23\r\n"
				+ "b 1\r\n" + "ddcb 11\r\n" + "dcab 16\r\n" + "cad 1\r\n" + "abba 8\r\n" + "ca 2\r\n" + "bb 17\r\n"
				+ "b 16\r\n" + "cc 24\r\n" + "a 8\r\n" + "aab 4\r\n" + "ac 8\r\n" + "aaccc 13\r\n" + "dadcb 2\r\n"
				+ "acd 6\r\n" + "d 16\r\n" + "acaac 0\r\n" + "c 9\r\n" + "cbbad 5\r\n" + "dcc 15\r\n" + "dabc 3\r\n"
				+ "bdabc 18\r\n" + "abbcd 0\r\n" + "ab 12\r\n" + "aadcc 6\r\n" + "badd 7\r\n" + "abbcd 13\r\n"
				+ "dc 17\r\n" + "cb 19\r\n" + "ccccc 21\r\n" + "accb 5\r\n" + "aabac 18\r\n" + "bac 14\r\n" + "d 2\r\n"
				+ "aad 18\r\n" + "baadb 16\r\n" + "dba 19\r\n" + "abbc 15\r\n" + "aacb 21\r\n" + "ddc 11\r\n"
				+ "bbdb 2\r\n" + "cbab 15\r\n" + "bdb 11\r\n" + "ddbdd 21\r\n" + "bbaaa 10\r\n" + "bbccc 12\r\n"
				+ "abccc 8\r\n" + "dddcc 11\r\n" + "bd 0\r\n" + "bcdb 10\r\n" + "cd 5\r\n" + "babb 9\r\n"
				+ "aaacd 2\r\n" + "bbbdc 11\r\n" + "a 13\r\n" + "dccba 4\r\n" + "bdbc 2\r\n" + "cadcc 14\r\n"
				+ "dd 19\r\n" + "d 0\r\n" + "bbcba 19\r\n" + "bb 10\r\n" + "cadbb 23\r\n" + "bbc 0\r\n" + "ddcc 1\r\n"
				+ "cbcdd 23\r\n" + "aab 13\r\n" + "da 6\r\n" + "bdaba 23\r\n" + "aaca 21\r\n" + "aad 11\r\n"
				+ "cadcb 3\r\n" + "dad 6\r\n" + "cbb 13\r\n" + "c 12\r\n" + "cadc 18\r\n" + "cadd 10\r\n" + "a 9\r\n"
				+ "b 14\r\n" + "abd 8\r\n" + "b 9\r\n" + "acd 3\r\n" + "ca 7\r\n" + "add 11\r\n" + "c 23\r\n"
				+ "c 7\r\n" + "dcd 19\r\n" + "ddda 14\r\n" + "ac 5\r\n" + "bc 4\r\n" + "db 13\r\n" + "bbaa 11\r\n"
				+ "bacd 20\r\n" + "c 0\r\n" + "c 5\r\n" + "dacda 4\r\n" + "b 22\r\n" + "c 11\r\n" + "dbdd 17\r\n"
				+ "adbd 0\r\n" + "cc 21\r\n" + "badbd 23\r\n" + "da 9\r\n" + "bcda 13\r\n" + "ab 15\r\n" + "bcd 22\r\n"
				+ "c 17\r\n" + "c 16\r\n" + "d 14\r\n" + "caab 23\r\n" + "ac 5\r\n" + "ddbda 17\r\n" + "cdb 11\r\n"
				+ "d 3\r\n" + "cbbb 10\r\n" + "dd 23\r\n" + "a 1\r\n" + "dcacb 22\r\n" + "cc 0\r\n" + "bdd 17\r\n"
				+ "bbbcc 20\r\n" + "cbacb 20\r\n" + "b 5\r\n" + "cc 9\r\n" + "d 17\r\n" + "bdcbc 16\r\n" + "db 5\r\n"
				+ "ad 17\r\n" + "a 13\r\n" + "bacca 17\r\n" + "cdabd 9\r\n" + "cadba 17\r\n" + "bacbd 13\r\n"
				+ "ddda 11\r\n" + "dddd 13\r\n" + "dccbb 14\r\n" + "ab 7\r\n" + "cca 24\r\n" + "a 14\r\n" + "d 18\r\n"
				+ "a 6\r\n" + "d 12\r\n" + "cadc 7\r\n" + "dabaa 5\r\n" + "abdb 7\r\n" + "bb 19\r\n" + "bcabc 6\r\n"
				+ "c 22\r\n" + "bad 7\r\n" + "dad 4\r\n" + "aaad 4\r\n" + "dcc 2\r\n" + "aadbc 17\r\n" + "bbbcb 23\r\n"
				+ "aab 17\r\n" + "a 14\r\n" + "accbb 10\r\n" + "dad 5\r\n" + "accbd 2\r\n" + "baaca 15\r\n"
				+ "dbdcc 6\r\n" + "aacb 11\r\n" + "bd 16\r\n" + "ad 9\r\n" + "cd 15\r\n" + "da 20\r\n" + "bcdc 8\r\n"
				+ "abda 20\r\n" + "cbddb 19\r\n" + "ba 23\r\n" + "dd 17\r\n" + "cdbca 18\r\n" + "cbacc 20\r\n"
				+ "dab 23\r\n" + "acbbd 19\r\n" + "baaad 23\r\n" + "bbaa 10\r\n" + "bdb 2\r\n" + "ad 22\r\n"
				+ "ac 16\r\n" + "ddbb 21\r\n" + "b 24\r\n" + "bcdc 10\r\n" + "c 22\r\n" + "aba 7\r\n" + "acccc 10\r\n"
				+ "aa 18\r\n" + "bdacd 0\r\n" + "bcbb 13\r\n" + "daaba 1\r\n" + "a 7\r\n" + "cadcb 6\r\n" + "caac 0\r\n"
				+ "bcb 6\r\n" + "cbdb 3\r\n" + "cb 3\r\n" + "b 12\r\n" + "abacc 7\r\n" + "bdad 22\r\n" + "bab 18\r\n"
				+ "db 24\r\n" + "ccdd 5\r\n" + "bcdb 15\r\n" + "dcddd 3\r\n" + "dbaab 12\r\n" + "aacda 0\r\n"
				+ "dad 6\r\n" + "cb 15\r\n" + "bba 11\r\n" + "adbd 18\r\n" + "dbcd 16\r\n" + "bbccd 17\r\n" + "d 0\r\n"
				+ "babd 11\r\n" + "dcddb 11\r\n" + "cbb 9\r\n" + "bbbc 15\r\n" + "ac 20\r\n" + "bb 9\r\n" + "c 7\r\n"
				+ "dbbba 17\r\n" + "bdb 15\r\n" + "a 4\r\n" + "cdabd 4\r\n" + "bd 19\r\n" + "adbdb 18\r\n"
				+ "ccacb 6\r\n" + "c 22\r\n" + "ccda 8\r\n" + "bba 4\r\n" + "d 0\r\n" + "db 1\r\n" + "c 20\r\n"
				+ "ab 21\r\n" + "caaaa 14\r\n" + "c 9\r\n" + "a 23\r\n" + "bbb 4\r\n" + "dba 22\r\n" + "cdcba 9\r\n"
				+ "d 8\r\n" + "dbbca 9\r\n" + "dd 19\r\n" + "ad 20\r\n" + "dab 14\r\n" + "acbdd 23\r\n" + "daadd 19\r\n"
				+ "bbab 12\r\n" + "daacb 4\r\n" + "bb 1\r\n" + "b 18\r\n" + "a 9\r\n" + "d 20\r\n" + "d 7\r\n"
				+ "a 21\r\n" + "cbdc 22\r\n" + "c 9\r\n" + "dac 18\r\n" + "dadca 3\r\n" + "bc 23\r\n" + "bbc 20\r\n"
				+ "aa 24\r\n" + "cac 24\r\n" + "dabb 8\r\n" + "abbc 15\r\n" + "ccdd 21\r\n" + "add 2\r\n" + "d 1\r\n"
				+ "bcccd 20\r\n" + "a 0\r\n" + "ccca 21\r\n" + "bccab 20\r\n" + "bbaa 4\r\n" + "d 15\r\n"
				+ "bcda 23\r\n" + "ab 17\r\n" + "db 12\r\n" + "a 6\r\n" + "cacb 21\r\n" + "cc 6\r\n" + "cdad 16\r\n"
				+ "cbc 2\r\n" + "d 19\r\n" + "db 20\r\n" + "baaa 20\r\n" + "bccd 7\r\n" + "ddcd 2\r\n" + "bab 22\r\n"
				+ "ddbac 20\r\n" + "aaa 1\r\n" + "adbd 1\r\n" + "aaddd 14\r\n" + "cab 14\r\n" + "dcca 23\r\n"
				+ "dcb 23\r\n" + "bdd 0\r\n" + "ccac 8\r\n" + "bbc 16\r\n" + "cddc 20\r\n" + "adab 10\r\n" + "cb 23\r\n"
				+ "aaaa 19\r\n" + "aaaa 4\r\n" + "ddc 9\r\n" + "b 19\r\n" + "daa 10\r\n" + "cd 11\r\n" + "a 9\r\n"
				+ "bcdd 11\r\n" + "aba 8\r\n" + "dbbba 14\r\n" + "bcacc 0\r\n" + "ba 2\r\n" + "ddc 8\r\n" + "ccd 17\r\n"
				+ "ddc 13\r\n" + "daab 15\r\n" + "db 7\r\n" + "ca 9\r\n" + "aa 24\r\n" + "cdda 4\r\n" + "cabc 11\r\n"
				+ "cba 24\r\n" + "bbc 13\r\n" + "aabcd 0\r\n" + "bcb 10\r\n" + "b 16\r\n" + "adac 8\r\n" + "a 0\r\n"
				+ "d 7\r\n" + "aaab 11\r\n" + "dd 24\r\n" + "bcd 0\r\n" + "aa 7\r\n" + "aadcc 13\r\n" + "b 16\r\n"
				+ "dacdb 20\r\n" + "c 17\r\n" + "caa 20\r\n" + "dddd 21\r\n" + "dbbb 19\r\n" + "daa 5\r\n" + "a 13\r\n"
				+ "bad 2\r\n" + "ccd 24\r\n" + "cb 5\r\n" + "a 3\r\n" + "daaa 2\r\n" + "aacb 24\r\n" + "bda 5\r\n"
				+ "aaa 20\r\n" + "c 13\r\n" + "ac 16\r\n" + "b 21\r\n" + "cca 8\r\n" + "ac 20\r\n" + "c 4\r\n"
				+ "bcb 17\r\n" + "bdabc 10\r\n" + "cd 18\r\n" + "bccda 21\r\n" + "bdda 12\r\n" + "cbdac 2\r\n"
				+ "dcd 9\r\n" + "adca 6\r\n" + "bcdad 0\r\n" + "acaa 15\r\n" + "cac 16\r\n" + "bbc 22\r\n" + "ca 9\r\n"
				+ "cbbdc 8\r\n" + "cdb 13\r\n" + "dadd 9\r\n" + "dadc 21\r\n" + "abc 0\r\n" + "dadbb 14\r\n"
				+ "bcc 14\r\n" + "bdd 13\r\n" + "ca 4\r\n" + "ad 11\r\n" + "a 20\r\n" + "cc 0\r\n" + "cd 23\r\n"
				+ "ccbaa 20\r\n" + "b 10\r\n" + "d 18\r\n" + "ddcd 23\r\n" + "bcba 5\r\n" + "ab 18\r\n" + "abccc 22\r\n"
				+ "dd 15\r\n" + "ccad 9\r\n" + "bbbdc 22\r\n" + "ddada 24\r\n" + "adccb 20\r\n" + "aaab 6\r\n"
				+ "bba 8\r\n" + "b 10\r\n" + "da 20\r\n" + "ddcdb 11\r\n" + "ad 21\r\n" + "adc 1\r\n" + "dc 13\r\n"
				+ "dbac 10\r\n" + "acbd 0\r\n" + "ccd 21\r\n" + "da 10\r\n" + "ca 23\r\n" + "aad 3\r\n" + "dcdda 14\r\n"
				+ "adbda 5\r\n" + "cacca 20\r\n" + "cacda 12\r\n" + "d 15\r\n" + "cadba 15\r\n" + "ba 11\r\n"
				+ "adcda 20\r\n" + "addc 1\r\n" + "baaa 24\r\n" + "ac 5\r\n" + "dcb 9\r\n" + "b 20\r\n" + "cdcbd 5\r\n"
				+ "dbc 9\r\n" + "d 9\r\n" + "dcabc 21\r\n" + "c 19\r\n" + "d 3\r\n" + "b 0\r\n" + "d 16\r\n" + "a 4\r\n"
				+ "c 22\r\n" + "aacac 22\r\n" + "adad 4\r\n" + "ba 11\r\n" + "ddcb 14\r\n" + "ddbd 8\r\n"
				+ "ddadb 23\r\n" + "adc 10\r\n" + "bcddc 5\r\n" + "bb 18\r\n" + "dd 0\r\n" + "ab 20\r\n" + "aaddc 2\r\n"
				+ "cdac 2\r\n" + "aca 14\r\n" + "adccc 16\r\n" + "daba 2\r\n" + "a 18\r\n" + "ada 12\r\n" + "dbac 1\r\n"
				+ "adda 17\r\n" + "c 22\r\n" + "aa 7\r\n" + "bbbcb 14\r\n" + "bc 8\r\n" + "ac 24\r\n" + "adbad 5\r\n"
				+ "dadbb 1\r\n" + "b 20\r\n" + "cab 22\r\n" + "abada 11\r\n" + "bbb 22\r\n" + "bddc 19\r\n"
				+ "baaab 24\r\n" + "aadc 10\r\n" + "c 11\r\n" + "ccc 2\r\n" + "dbacc 9\r\n" + "acbbc 10\r\n"
				+ "ddaaa 12\r\n" + "ab 16\r\n" + "dc 3\r\n" + "cab 7\r\n" + "db 13\r\n" + "ccbda 3\r\n" + "dc 5\r\n"
				+ "cb 12\r\n" + "ccbb 15\r\n" + "ccd 9\r\n" + "dcdd 21\r\n" + "baab 16\r\n" + "b 6\r\n" + "aaac 18\r\n"
				+ "ab 13\r\n" + "d 4\r\n" + "cba 20\r\n" + "d 13\r\n" + "ad 0\r\n" + "ac 11\r\n" + "ab 16\r\n"
				+ "baad 8\r\n" + "ca 16\r\n" + "ddba 6\r\n" + "ddd 15\r\n" + "c 6\r\n" + "adab 11\r\n" + "cccc 4\r\n"
				+ "aacb 22\r\n" + "abcc 14\r\n" + "bbb 6\r\n" + "c 1\r\n" + "cbad 6\r\n" + "bbbdd 6\r\n" + "ccaac 3\r\n"
				+ "a 19\r\n" + "bbbaa 21\r\n" + "dbda 15\r\n" + "c 6\r\n" + "dbaab 24\r\n" + "ccba 4\r\n" + "add 17\r\n"
				+ "dba 12\r\n" + "bba 20\r\n" + "da 7\r\n" + "baddc 12\r\n" + "acb 5\r\n" + "bad 20\r\n" + "c 19\r\n"
				+ "adcba 18\r\n" + "da 13\r\n" + "bca 3\r\n" + "cbbac 3\r\n" + "dbdbc 19\r\n" + "ccaa 11\r\n"
				+ "a 19\r\n" + "abac 1\r\n" + "ca 24\r\n" + "b 11\r\n" + "ca 24\r\n" + "ddcb 14\r\n" + "d 6\r\n"
				+ "cab 6\r\n" + "ca 18\r\n" + "dacd 20\r\n" + "adb 13\r\n" + "d 21\r\n" + "c 23\r\n" + "cbdcc 21\r\n"
				+ "a 4\r\n" + "cabc 13\r\n" + "a 3\r\n" + "daaa 3\r\n" + "dcb 21\r\n" + "baabc 16\r\n" + "b 16\r\n"
				+ "cbadd 20\r\n" + "d 23\r\n" + "cdcc 18\r\n" + "bac 4\r\n" + "a 7\r\n" + "bbd 11\r\n" + "cdbd 4\r\n"
				+ "cdbb 23\r\n" + "ac 11\r\n" + "bca 3\r\n" + "dbb 5\r\n" + "cdac 22\r\n" + "bd 1\r\n" + "d 14\r\n"
				+ "badaa 0\r\n" + "ddad 12\r\n" + "cbca 21\r\n" + "dccba 3\r\n" + "bba 22\r\n" + "bbb 8\r\n"
				+ "dd 17\r\n" + "adcb 11\r\n" + "abca 20\r\n" + "dcbd 24\r\n" + "ad 18\r\n" + "aac 15\r\n" + "bbc 5\r\n"
				+ "cccdc 19\r\n" + "a 1\r\n" + "bca 23\r\n" + "dcb 12\r\n" + "cccba 24\r\n" + "b 17\r\n" + "caaa 3\r\n"
				+ "db 10\r\n" + "d 23\r\n" + "ddb 15\r\n" + "cbcaa 12\r\n" + "aaabd 15\r\n" + "dc 18\r\n"
				+ "acaca 1\r\n" + "ad 16\r\n" + "ccd 3\r\n" + "ad 10\r\n" + "dc 11\r\n" + "bddab 21\r\n" + "b 3\r\n"
				+ "ac 20\r\n" + "cdaab 3\r\n" + "a 1\r\n" + "abb 1\r\n" + "caac 3\r\n" + "dca 24\r\n" + "b 7\r\n"
				+ "bda 22\r\n" + "ab 5\r\n" + "bb 8\r\n" + "cab 8\r\n" + "b 5\r\n" + "acad 4\r\n" + "ddcb 20\r\n"
				+ "babc 21\r\n" + "cdbba 8\r\n" + "bbbc 24\r\n" + "dacc 6\r\n" + "bccc 6\r\n" + "ddcb 24\r\n"
				+ "da 4\r\n" + "acd 24\r\n" + "aabcd 12\r\n" + "bb 14\r\n" + "d 2\r\n" + "c 12\r\n" + "cb 15\r\n"
				+ "dbd 20\r\n" + "ddbb 21\r\n" + "cadbc 9\r\n" + "dabc 3\r\n" + "bccd 13\r\n" + "cd 5\r\n" + "a 3\r\n"
				+ "adcc 11\r\n" + "cdbad 13\r\n" + "dc 19\r\n" + "a 10\r\n" + "cca 4\r\n" + "dcb 8\r\n" + "b 22\r\n"
				+ "dcad 8\r\n" + "bbdbb 9\r\n" + "dadc 18\r\n" + "abd 22\r\n" + "bbabc 13\r\n" + "cd 11\r\n"
				+ "acc 12\r\n" + "acddb 21\r\n" + "dd 10\r\n" + "add 19\r\n" + "a 8\r\n" + "dc 7\r\n" + "bbcbd 20\r\n"
				+ "abb 5\r\n" + "cc 19\r\n" + "c 5\r\n" + "cdb 3\r\n" + "bbc 18\r\n" + "bb 8\r\n" + "abcb 9\r\n"
				+ "c 14\r\n" + "c 20\r\n" + "cbdcc 15\r\n" + "dbb 4\r\n" + "d 24\r\n" + "bd 6\r\n" + "dcc 10\r\n"
				+ "bcc 9\r\n" + "bb 12\r\n" + "aaabc 8\r\n" + "dbadc 22\r\n" + "b 3\r\n" + "aacac 11\r\n" + "aa 15\r\n"
				+ "b 4\r\n" + "bc 23\r\n" + "adbd 18\r\n" + "cddca 7\r\n" + "bcbb 20\r\n" + "aab 16\r\n" + "caad 12\r\n"
				+ "bcdcc 6\r\n" + "a 15\r\n" + "ddaba 7\r\n" + "bcd 3\r\n" + "a 19\r\n" + "cbdb 4\r\n" + "dc 7\r\n"
				+ "abbaa 5\r\n" + "dbbdd 8\r\n" + "cdc 19\r\n" + "c 5\r\n" + "dd 4\r\n" + "ccba 8\r\n" + "cbbcc 12\r\n"
				+ "dcacb 5\r\n" + "acbab 11\r\n" + "aabd 0\r\n" + "a 24\r\n" + "b 18\r\n" + "dddaa 20\r\n"
				+ "abd 13\r\n" + "adc 2\r\n" + "dcbad 7\r\n" + "db 7\r\n" + "cabb 23\r\n" + "badda 10\r\n"
				+ "bbdba 15\r\n" + "dbc 2\r\n" + "d 10\r\n" + "ab 9\r\n" + "baa 21\r\n" + "baabb 18\r\n" + "cbddb 0\r\n"
				+ "bd 1\r\n" + "dcdd 11\r\n" + "dbbdb 8\r\n" + "cca 22\r\n" + "adb 23\r\n" + "bd 8\r\n" + "ad 24\r\n"
				+ "d 8\r\n" + "cc 7\r\n" + "dbb 14\r\n" + "bdacc 22\r\n" + "cb 19\r\n" + "ca 10\r\n" + "aab 6\r\n"
				+ "b 24\r\n" + "ab 18\r\n" + "caabc 18\r\n" + "abb 0\r\n" + "cdaad 23\r\n" + "dbbbb 23\r\n" + "dd 0\r\n"
				+ "cc 6\r\n" + "dbb 21\r\n" + "dcd 3\r\n" + "cc 13\r\n" + "d 4\r\n" + "bb 13\r\n" + "aa 16\r\n"
				+ "adcd 15\r\n" + "cdc 20\r\n" + "b 0\r\n" + "d 21\r\n" + "cb 22\r\n" + "bbc 11\r\n" + "addb 3\r\n"
				+ "bbdd 7\r\n" + "d 4\r\n" + "dacd 19\r\n" + "ccbcd 13\r\n" + "cc 4\r\n" + "bbaa 18\r\n" + "b 4\r\n"
				+ "dcdcd 6\r\n" + "bcdb 0\r\n" + "dc 24\r\n" + "b 6\r\n" + "dbbbb 16\r\n" + "cdd 24\r\n" + "bc 2\r\n"
				+ "b 12\r\n" + "ddd 24\r\n" + "ccaaa 12\r\n" + "dabab 9\r\n" + "ddc 0\r\n" + "d 19\r\n" + "dacaa 24\r\n"
				+ "abbcc 0\r\n" + "b 11\r\n" + "bdccc 5\r\n" + "bdcdc 1\r\n" + "bca 7\r\n" + "bbcdd 16\r\n"
				+ "adc 18\r\n" + "d 0\r\n" + "bd 13\r\n" + "bb 2\r\n" + "d 3\r\n" + "bbb 11\r\n" + "d 19\r\n"
				+ "cddd 9\r\n" + "b 2\r\n" + "adab 20\r\n" + "ddc 21\r\n" + "ccbdd 19\r\n" + "cbc 13\r\n" + "cdc 1\r\n"
				+ "dac 19\r\n" + "cabdd 11\r\n" + "da 14\r\n" + "bda 14\r\n" + "c 5\r\n" + "dbbc 4\r\n" + "a 18\r\n"
				+ "c 12\r\n" + "ad 8\r\n" + "cb 12\r\n" + "b 3\r\n" + "dbcdc 4\r\n" + "bab 21\r\n" + "bc 13\r\n"
				+ "cbcac 0\r\n" + "c 21\r\n" + "ab 8\r\n" + "acd 9\r\n" + "bdbc 4\r\n" + "b 21\r\n" + "ab 7\r\n"
				+ "ccc 8\r\n" + "dcaa 22\r\n" + "dabbd 14\r\n" + "a 4\r\n" + "ddda 7\r\n" + "acdc 4\r\n" + "bbb 15\r\n"
				+ "b 0\r\n" + "daca 14\r\n" + "aa 7\r\n" + "ab 2\r\n" + "c 9\r\n" + "ccbb 10\r\n" + "cda 15\r\n"
				+ "bcba 9\r\n" + "bab 18\r\n" + "abab 13\r\n" + "dabc 3\r\n" + "dbab 16\r\n" + "ddc 19\r\n"
				+ "caa 3\r\n" + "b 24\r\n" + "bcad 1\r\n" + "cdaa 6\r\n" + "ddcad 21\r\n" + "dbbd 23\r\n" + "dd 18\r\n"
				+ "abc 13\r\n" + "bb 24\r\n" + "baa 23\r\n" + "ac 19\r\n" + "bd 15\r\n" + "aba 18\r\n" + "ddda 23\r\n"
				+ "dbbad 1\r\n" + "abbdd 23\r\n" + "d 6\r\n" + "dbd 7\r\n" + "ddac 22\r\n" + "dbdcd 17\r\n"
				+ "cbd 7\r\n" + "abbb 19\r\n" + "caaad 4\r\n" + "cdd 0\r\n" + "ca 6\r\n" + "ccca 4\r\n" + "dccd 17\r\n"
				+ "a 13\r\n" + "db 18\r\n" + "babdd 24\r\n" + "bdaa 9\r\n" + "cdd 21\r\n" + "caccd 0\r\n" + "ad 3\r\n"
				+ "aacac 17\r\n" + "ccbbd 16\r\n" + "bdcab 17\r\n" + "b 5\r\n" + "a 7\r\n" + "aa 22\r\n" + "a 1\r\n"
				+ "bd 3\r\n" + "cacd 1\r\n" + "cbcab 9\r\n" + "aa 4\r\n" + "a 13\r\n" + "adcbd 9\r\n" + "ad 9\r\n"
				+ "b 5\r\n" + "adcc 15\r\n" + "ccdac 12\r\n" + "addb 9\r\n" + "d 5\r\n" + "cccbc 16\r\n" + "cd 13\r\n"
				+ "cbcc 21\r\n" + "cac 23\r\n" + "cbad 16\r\n" + "c 23\r\n" + "ba 1\r\n" + "cdba 9\r\n" + "bbbd 20\r\n"
				+ "dbbc 7\r\n" + "aada 7\r\n" + "c 6\r\n" + "dccc 9\r\n" + "dab 23\r\n" + "cab 20\r\n" + "addcc 13\r\n"
				+ "cbdcd 14\r\n" + "cbca 7\r\n" + "cc 1\r\n" + "babbb 10\r\n" + "bc 21\r\n" + "abdcc 13\r\n"
				+ "bdbd 6\r\n" + "ddccb 4\r\n" + "c 20\r\n" + "a 16\r\n" + "d 9\r\n" + "cda 0\r\n" + "c 9\r\n"
				+ "ccdd 15\r\n" + "dbdbd 17\r\n" + "a 13\r\n" + "dddb 11\r\n" + "b 0\r\n" + "bbd 15\r\n" + "dcbdb 13");
		case3.setOutput("a 24\r\n" + "aa 24\r\n" + "aa 24\r\n" + "aacb 24\r\n" + "ac 24\r\n" + "acd 24\r\n"
				+ "ad 24\r\n" + "addb 24\r\n" + "b 24\r\n" + "b 24\r\n" + "b 24\r\n" + "baaa 24\r\n" + "baaab 24\r\n"
				+ "babdd 24\r\n" + "bb 24\r\n" + "bbbc 24\r\n" + "ca 24\r\n" + "ca 24\r\n" + "cac 24\r\n" + "cba 24\r\n"
				+ "cc 24\r\n" + "cca 24\r\n" + "cccba 24\r\n" + "ccd 24\r\n" + "cda 24\r\n" + "cdd 24\r\n" + "d 24\r\n"
				+ "dacaa 24\r\n" + "db 24\r\n" + "dbaab 24\r\n" + "dc 24\r\n" + "dca 24\r\n" + "dcbd 24\r\n"
				+ "dd 24\r\n" + "dd 24\r\n" + "ddada 24\r\n" + "ddcb 24\r\n" + "ddd 24\r\n" + "a 23\r\n"
				+ "abbdd 23\r\n" + "acbdd 23\r\n" + "adb 23\r\n" + "ba 23\r\n" + "baa 23\r\n" + "baaad 23\r\n"
				+ "badbd 23\r\n" + "bbbcb 23\r\n" + "bc 23\r\n" + "bc 23\r\n" + "bca 23\r\n" + "bcda 23\r\n"
				+ "bdaba 23\r\n" + "c 23\r\n" + "c 23\r\n" + "c 23\r\n" + "ca 23\r\n" + "caab 23\r\n" + "cabab 23\r\n"
				+ "cabb 23\r\n" + "cac 23\r\n" + "cadbb 23\r\n" + "cb 23\r\n" + "cbcdd 23\r\n" + "cd 23\r\n"
				+ "cdaad 23\r\n" + "cdbb 23\r\n" + "d 23\r\n" + "d 23\r\n" + "daadd 23\r\n" + "dab 23\r\n"
				+ "dab 23\r\n" + "dbbbb 23\r\n" + "dbbd 23\r\n" + "dc 23\r\n" + "dcb 23\r\n" + "dcca 23\r\n"
				+ "dd 23\r\n" + "ddadb 23\r\n" + "ddcd 23\r\n" + "ddda 23\r\n" + "aa 22\r\n" + "aacac 22\r\n"
				+ "aacb 22\r\n" + "abccc 22\r\n" + "abd 22\r\n" + "ad 22\r\n" + "b 22\r\n" + "b 22\r\n" + "baabd 22\r\n"
				+ "bab 22\r\n" + "bba 22\r\n" + "bbb 22\r\n" + "bbbdc 22\r\n" + "bbc 22\r\n" + "bcd 22\r\n"
				+ "bcdb 22\r\n" + "bda 22\r\n" + "bdaac 22\r\n" + "bdacc 22\r\n" + "bdad 22\r\n" + "c 22\r\n"
				+ "c 22\r\n" + "c 22\r\n" + "c 22\r\n" + "c 22\r\n" + "cab 22\r\n" + "cb 22\r\n" + "cbdaa 22\r\n"
				+ "cbdc 22\r\n" + "cca 22\r\n" + "cdac 22\r\n" + "dba 22\r\n" + "dbadc 22\r\n" + "dcaa 22\r\n"
				+ "dcacb 22\r\n" + "ddac 22\r\n" + "a 21\r\n" + "a 21\r\n" + "aaca 21\r\n" + "aacb 21\r\n" + "ab 21\r\n"
				+ "acddb 21\r\n" + "ad 21\r\n" + "b 21\r\n" + "b 21\r\n" + "baa 21\r\n" + "bab 21\r\n" + "babc 21\r\n"
				+ "bbbaa 21\r\n" + "bc 21\r\n" + "bc 21\r\n" + "bccda 21\r\n" + "bddab 21\r\n" + "c 21\r\n"
				+ "ca 21\r\n" + "cacb 21\r\n" + "cbca 21\r\n" + "cbcc 21\r\n" + "cbdcc 21\r\n" + "cc 21\r\n"
				+ "ccca 21\r\n" + "ccccc 21\r\n" + "ccd 21\r\n" + "ccdd 21\r\n" + "cdd 21\r\n" + "d 21\r\n" + "d 21\r\n"
				+ "dadc 21\r\n" + "dbb 21\r\n" + "dbcc 21\r\n" + "dcabc 21\r\n" + "dcb 21\r\n" + "dcdd 21\r\n"
				+ "dd 21\r\n" + "ddbb 21\r\n" + "ddbb 21\r\n" + "ddbdd 21\r\n" + "ddc 21\r\n" + "ddcad 21\r\n"
				+ "dddd 21\r\n" + "a 20\r\n" + "aaa 20\r\n" + "ab 20\r\n" + "ab 20\r\n" + "abca 20\r\n" + "abda 20\r\n"
				+ "ac 20\r\n" + "ac 20\r\n" + "ac 20\r\n" + "ad 20\r\n" + "ada 20\r\n" + "adab 20\r\n" + "adccb 20\r\n"
				+ "adcda 20\r\n" + "b 20\r\n" + "b 20\r\n" + "baaa 20\r\n" + "bacd 20\r\n" + "bad 20\r\n" + "bba 20\r\n"
				+ "bbbcc 20\r\n" + "bbbd 20\r\n" + "bbc 20\r\n" + "bbcbd 20\r\n" + "bcbb 20\r\n" + "bccab 20\r\n"
				+ "bcccd 20\r\n" + "c 20\r\n" + "c 20\r\n" + "c 20\r\n" + "caa 20\r\n" + "cab 20\r\n" + "cacca 20\r\n"
				+ "cadab 20\r\n" + "cba 20\r\n" + "cbacb 20\r\n" + "cbacc 20\r\n" + "cbadd 20\r\n" + "ccbaa 20\r\n"
				+ "cdc 20\r\n" + "cddc 20\r\n" + "d 20\r\n" + "da 20\r\n" + "da 20\r\n" + "dacd 20\r\n" + "dacdb 20\r\n"
				+ "db 20\r\n" + "dbd 20\r\n" + "dc 20\r\n" + "ddbac 20\r\n" + "ddcb 20\r\n" + "dddaa 20\r\n"
				+ "a 19\r\n" + "a 19\r\n" + "a 19\r\n" + "aaaa 19\r\n" + "abbb 19\r\n" + "ac 19\r\n" + "acbbd 19\r\n"
				+ "add 19\r\n" + "b 19\r\n" + "bb 19\r\n" + "bbcba 19\r\n" + "bd 19\r\n" + "bddc 19\r\n" + "c 19\r\n"
				+ "c 19\r\n" + "cb 19\r\n" + "cb 19\r\n" + "cbddb 19\r\n" + "cc 19\r\n" + "cca 19\r\n" + "ccbdd 19\r\n"
				+ "cccdc 19\r\n" + "cdc 19\r\n" + "d 19\r\n" + "d 19\r\n" + "d 19\r\n" + "d 19\r\n" + "daadd 19\r\n"
				+ "dac 19\r\n" + "dacd 19\r\n" + "dba 19\r\n" + "dbbb 19\r\n" + "dbdbc 19\r\n" + "dc 19\r\n"
				+ "dcd 19\r\n" + "dd 19\r\n" + "dd 19\r\n" + "ddc 19\r\n" + "a 18\r\n" + "a 18\r\n" + "aa 18\r\n"
				+ "aaac 18\r\n" + "aabac 18\r\n" + "aabdd 18\r\n" + "aad 18\r\n" + "ab 18\r\n" + "ab 18\r\n"
				+ "aba 18\r\n" + "abdd 18\r\n" + "ad 18\r\n" + "adbd 18\r\n" + "adbd 18\r\n" + "adbdb 18\r\n"
				+ "adc 18\r\n" + "adcba 18\r\n" + "b 18\r\n" + "b 18\r\n" + "baabb 18\r\n" + "bab 18\r\n" + "bab 18\r\n"
				+ "bb 18\r\n" + "bbaa 18\r\n" + "bbc 18\r\n" + "bdabc 18\r\n" + "ca 18\r\n" + "caabc 18\r\n"
				+ "cadc 18\r\n" + "ccabc 18\r\n" + "cd 18\r\n" + "cdbca 18\r\n" + "cdcc 18\r\n" + "d 18\r\n"
				+ "d 18\r\n" + "daabd 18\r\n" + "dac 18\r\n" + "dadc 18\r\n" + "db 18\r\n" + "dc 18\r\n" + "dd 18\r\n"
				+ "aab 17\r\n" + "aacac 17\r\n" + "aadbc 17\r\n" + "ab 17\r\n" + "ad 17\r\n" + "adbab 17\r\n"
				+ "add 17\r\n" + "adda 17\r\n" + "b 17\r\n" + "b 17\r\n" + "bacca 17\r\n" + "bb 17\r\n" + "bbccd 17\r\n"
				+ "bcb 17\r\n" + "bdcab 17\r\n" + "bdd 17\r\n" + "c 17\r\n" + "c 17\r\n" + "cadba 17\r\n" + "ccd 17\r\n"
				+ "cd 17\r\n" + "d 17\r\n" + "dbbba 17\r\n" + "dbdbd 17\r\n" + "dbdcd 17\r\n" + "dbdd 17\r\n"
				+ "dc 17\r\n" + "dccd 17\r\n" + "dd 17\r\n" + "dd 17\r\n" + "ddbda 17\r\n" + "a 16\r\n" + "aa 16\r\n"
				+ "aab 16\r\n" + "ab 16\r\n" + "ab 16\r\n" + "ac 16\r\n" + "ac 16\r\n" + "ad 16\r\n" + "adccc 16\r\n"
				+ "b 16\r\n" + "b 16\r\n" + "b 16\r\n" + "b 16\r\n" + "b 16\r\n" + "baab 16\r\n" + "baabc 16\r\n"
				+ "baadb 16\r\n" + "bbc 16\r\n" + "bbcdd 16\r\n" + "bd 16\r\n" + "bdc 16\r\n" + "bdcbc 16\r\n"
				+ "c 16\r\n" + "ca 16\r\n" + "cac 16\r\n" + "cadb 16\r\n" + "cbad 16\r\n" + "ccbbd 16\r\n"
				+ "cccbc 16\r\n" + "cd 16\r\n" + "cdad 16\r\n" + "d 16\r\n" + "d 16\r\n" + "dbab 16\r\n"
				+ "dbbbb 16\r\n" + "dbcd 16\r\n" + "dcab 16\r\n" + "a 15\r\n" + "aa 15\r\n" + "aaabd 15\r\n"
				+ "aac 15\r\n" + "ab 15\r\n" + "abbc 15\r\n" + "abbc 15\r\n" + "acaa 15\r\n" + "adcc 15\r\n"
				+ "adcd 15\r\n" + "baaca 15\r\n" + "bbb 15\r\n" + "bbbc 15\r\n" + "bbd 15\r\n" + "bbdba 15\r\n"
				+ "bcdb 15\r\n" + "bd 15\r\n" + "bdb 15\r\n" + "cadba 15\r\n" + "cb 15\r\n" + "cb 15\r\n"
				+ "cbab 15\r\n" + "cbdcc 15\r\n" + "ccbb 15\r\n" + "ccdd 15\r\n" + "cd 15\r\n" + "cda 15\r\n"
				+ "d 15\r\n" + "d 15\r\n" + "daab 15\r\n" + "dbda 15\r\n" + "dcc 15\r\n" + "dd 15\r\n" + "ddb 15\r\n"
				+ "ddd 15\r\n" + "a 14\r\n" + "a 14\r\n" + "aaddd 14\r\n" + "abcc 14\r\n" + "aca 14\r\n" + "b 14\r\n"
				+ "bac 14\r\n" + "bacba 14\r\n" + "bb 14\r\n" + "bbbcb 14\r\n" + "bcc 14\r\n" + "bda 14\r\n"
				+ "c 14\r\n" + "caaaa 14\r\n" + "caad 14\r\n" + "cab 14\r\n" + "cadcc 14\r\n" + "cbdcd 14\r\n"
				+ "d 14\r\n" + "d 14\r\n" + "da 14\r\n" + "dab 14\r\n" + "dabbd 14\r\n" + "daca 14\r\n" + "dadbb 14\r\n"
				+ "dbb 14\r\n" + "dbbba 14\r\n" + "dccbb 14\r\n" + "dcdda 14\r\n" + "ddcb 14\r\n" + "ddcb 14\r\n"
				+ "ddda 14\r\n" + "a 13\r\n" + "a 13\r\n" + "a 13\r\n" + "a 13\r\n" + "a 13\r\n" + "a 13\r\n"
				+ "aab 13\r\n" + "aaccc 13\r\n" + "aadcc 13\r\n" + "ab 13\r\n" + "abab 13\r\n" + "abb 13\r\n"
				+ "abbcd 13\r\n" + "abc 13\r\n" + "abd 13\r\n" + "abdcc 13\r\n" + "adb 13\r\n" + "addcc 13\r\n"
				+ "bacbd 13\r\n" + "bb 13\r\n" + "bbabc 13\r\n" + "bbc 13\r\n" + "bc 13\r\n" + "bcaa 13\r\n"
				+ "bcbb 13\r\n" + "bccd 13\r\n" + "bcda 13\r\n" + "bd 13\r\n" + "bdd 13\r\n" + "bddad 13\r\n"
				+ "c 13\r\n" + "cabc 13\r\n" + "cbb 13\r\n" + "cbc 13\r\n" + "cc 13\r\n" + "ccbcd 13\r\n" + "cd 13\r\n"
				+ "cdb 13\r\n" + "cdbad 13\r\n" + "d 13\r\n" + "da 13\r\n" + "db 13\r\n" + "db 13\r\n" + "dc 13\r\n"
				+ "dcbdb 13\r\n" + "ddc 13\r\n" + "dddd 13\r\n" + "aabcd 12\r\n" + "ab 12\r\n" + "acc 12\r\n"
				+ "accb 12\r\n" + "ada 12\r\n" + "b 12\r\n" + "b 12\r\n" + "baddc 12\r\n" + "bb 12\r\n" + "bbab 12\r\n"
				+ "bbccc 12\r\n" + "bdda 12\r\n" + "c 12\r\n" + "c 12\r\n" + "c 12\r\n" + "c 12\r\n" + "caad 12\r\n"
				+ "cacda 12\r\n" + "cb 12\r\n" + "cb 12\r\n" + "cbbcc 12\r\n" + "cbcaa 12\r\n" + "ccaaa 12\r\n"
				+ "ccdac 12\r\n" + "d 12\r\n" + "dabb 12\r\n" + "db 12\r\n" + "dba 12\r\n" + "dbaab 12\r\n"
				+ "dcb 12\r\n" + "ddaaa 12\r\n" + "ddad 12\r\n" + "ddc 12\r\n" + "aaab 11\r\n" + "aacac 11\r\n"
				+ "aacb 11\r\n" + "aad 11\r\n" + "abada 11\r\n" + "ac 11\r\n" + "ac 11\r\n" + "acbab 11\r\n"
				+ "ad 11\r\n" + "adaab 11\r\n" + "adab 11\r\n" + "adcb 11\r\n" + "adcc 11\r\n" + "add 11\r\n"
				+ "b 11\r\n" + "b 11\r\n" + "ba 11\r\n" + "ba 11\r\n" + "babd 11\r\n" + "bba 11\r\n" + "bbaa 11\r\n"
				+ "bbb 11\r\n" + "bbbdc 11\r\n" + "bbc 11\r\n" + "bbd 11\r\n" + "bcdd 11\r\n" + "bdb 11\r\n"
				+ "c 11\r\n" + "c 11\r\n" + "cabc 11\r\n" + "cabdd 11\r\n" + "cca 11\r\n" + "ccaa 11\r\n" + "cd 11\r\n"
				+ "cd 11\r\n" + "cdb 11\r\n" + "daad 11\r\n" + "dc 11\r\n" + "dcdd 11\r\n" + "dcddb 11\r\n"
				+ "dd 11\r\n" + "ddc 11\r\n" + "ddcb 11\r\n" + "ddcdb 11\r\n" + "ddda 11\r\n" + "dddb 11\r\n"
				+ "dddcc 11\r\n" + "a 10\r\n" + "aadc 10\r\n" + "ab 10\r\n" + "acbbc 10\r\n" + "accbb 10\r\n"
				+ "acccc 10\r\n" + "ad 10\r\n" + "ada 10\r\n" + "adab 10\r\n" + "adc 10\r\n" + "b 10\r\n" + "b 10\r\n"
				+ "babbb 10\r\n" + "badda 10\r\n" + "bb 10\r\n" + "bbaa 10\r\n" + "bbaaa 10\r\n" + "bcb 10\r\n"
				+ "bcdb 10\r\n" + "bcdc 10\r\n" + "bdabc 10\r\n" + "ca 10\r\n" + "cadd 10\r\n" + "cb 10\r\n"
				+ "cba 10\r\n" + "cbbb 10\r\n" + "ccbb 10\r\n" + "d 10\r\n" + "da 10\r\n" + "daa 10\r\n" + "db 10\r\n"
				+ "dbac 10\r\n" + "dcc 10\r\n" + "dd 10\r\n" + "ddbcd 10\r\n" + "a 9\r\n" + "a 9\r\n" + "a 9\r\n"
				+ "ab 9\r\n" + "abcb 9\r\n" + "acd 9\r\n" + "ad 9\r\n" + "ad 9\r\n" + "adcbd 9\r\n" + "addb 9\r\n"
				+ "b 9\r\n" + "b 9\r\n" + "babb 9\r\n" + "bb 9\r\n" + "bbdbb 9\r\n" + "bcba 9\r\n" + "bcc 9\r\n"
				+ "bdaa 9\r\n" + "c 9\r\n" + "c 9\r\n" + "c 9\r\n" + "c 9\r\n" + "c 9\r\n" + "c 9\r\n" + "ca 9\r\n"
				+ "ca 9\r\n" + "cadbc 9\r\n" + "cbb 9\r\n" + "cbcab 9\r\n" + "cc 9\r\n" + "ccad 9\r\n" + "ccd 9\r\n"
				+ "cdabd 9\r\n" + "cdba 9\r\n" + "cdcba 9\r\n" + "cdda 9\r\n" + "cddd 9\r\n" + "d 9\r\n" + "d 9\r\n"
				+ "d 9\r\n" + "da 9\r\n" + "dabab 9\r\n" + "dadd 9\r\n" + "dbacc 9\r\n" + "dbbca 9\r\n" + "dbc 9\r\n"
				+ "dcb 9\r\n" + "dccc 9\r\n" + "dcd 9\r\n" + "ddc 9\r\n" + "a 8\r\n" + "a 8\r\n" + "aaabc 8\r\n"
				+ "ab 8\r\n" + "aba 8\r\n" + "abba 8\r\n" + "abccc 8\r\n" + "abd 8\r\n" + "ac 8\r\n" + "ad 8\r\n"
				+ "adac 8\r\n" + "b 8\r\n" + "baad 8\r\n" + "bb 8\r\n" + "bb 8\r\n" + "bba 8\r\n" + "bbb 8\r\n"
				+ "bc 8\r\n" + "bcbb 8\r\n" + "bcdc 8\r\n" + "bd 8\r\n" + "cab 8\r\n" + "cbbdc 8\r\n" + "cca 8\r\n"
				+ "ccac 8\r\n" + "ccba 8\r\n" + "ccc 8\r\n" + "ccda 8\r\n" + "cdbba 8\r\n" + "d 8\r\n" + "d 8\r\n"
				+ "dabb 8\r\n" + "dbbdb 8\r\n" + "dbbdd 8\r\n" + "dcad 8\r\n" + "dcb 8\r\n" + "ddbd 8\r\n" + "ddc 8\r\n"
				+ "a 7\r\n" + "a 7\r\n" + "a 7\r\n" + "aa 7\r\n" + "aa 7\r\n" + "aa 7\r\n" + "aada 7\r\n" + "ab 7\r\n"
				+ "ab 7\r\n" + "ab 7\r\n" + "aba 7\r\n" + "abacc 7\r\n" + "abdb 7\r\n" + "b 7\r\n" + "bad 7\r\n"
				+ "badd 7\r\n" + "bbdd 7\r\n" + "bca 7\r\n" + "bccd 7\r\n" + "bd 7\r\n" + "c 7\r\n" + "c 7\r\n"
				+ "ca 7\r\n" + "cab 7\r\n" + "cadc 7\r\n" + "cbca 7\r\n" + "cbd 7\r\n" + "cc 7\r\n" + "ccdb 7\r\n"
				+ "cddca 7\r\n" + "d 7\r\n" + "d 7\r\n" + "d 7\r\n" + "da 7\r\n" + "db 7\r\n" + "db 7\r\n"
				+ "dbbc 7\r\n" + "dbd 7\r\n" + "dc 7\r\n" + "dc 7\r\n" + "dcbad 7\r\n" + "ddaba 7\r\n" + "ddda 7\r\n"
				+ "a 6\r\n" + "a 6\r\n" + "aaab 6\r\n" + "aab 6\r\n" + "aadcc 6\r\n" + "acd 6\r\n" + "adca 6\r\n"
				+ "b 6\r\n" + "b 6\r\n" + "baacd 6\r\n" + "bbb 6\r\n" + "bbbdd 6\r\n" + "bcabc 6\r\n" + "bcb 6\r\n"
				+ "bccc 6\r\n" + "bcdcc 6\r\n" + "bd 6\r\n" + "bdbd 6\r\n" + "c 6\r\n" + "c 6\r\n" + "c 6\r\n"
				+ "ca 6\r\n" + "caad 6\r\n" + "cab 6\r\n" + "cadcb 6\r\n" + "cbad 6\r\n" + "cc 6\r\n" + "cc 6\r\n"
				+ "ccaa 6\r\n" + "ccacb 6\r\n" + "cdaa 6\r\n" + "d 6\r\n" + "d 6\r\n" + "da 6\r\n" + "dacc 6\r\n"
				+ "dad 6\r\n" + "dad 6\r\n" + "dbdcc 6\r\n" + "dcdcd 6\r\n" + "ddba 6\r\n" + "ab 5\r\n" + "abb 5\r\n"
				+ "abbaa 5\r\n" + "ac 5\r\n" + "ac 5\r\n" + "ac 5\r\n" + "acb 5\r\n" + "accb 5\r\n" + "adbad 5\r\n"
				+ "adbda 5\r\n" + "b 5\r\n" + "b 5\r\n" + "b 5\r\n" + "b 5\r\n" + "bbc 5\r\n" + "bcba 5\r\n"
				+ "bcddc 5\r\n" + "bda 5\r\n" + "bdccc 5\r\n" + "c 5\r\n" + "c 5\r\n" + "c 5\r\n" + "c 5\r\n"
				+ "ca 5\r\n" + "cb 5\r\n" + "cbbad 5\r\n" + "ccdd 5\r\n" + "cd 5\r\n" + "cd 5\r\n" + "cdcbd 5\r\n"
				+ "d 5\r\n" + "daa 5\r\n" + "dabaa 5\r\n" + "dabdb 5\r\n" + "dad 5\r\n" + "db 5\r\n" + "dbb 5\r\n"
				+ "dc 5\r\n" + "dcacb 5\r\n" + "a 4\r\n" + "a 4\r\n" + "a 4\r\n" + "a 4\r\n" + "aa 4\r\n" + "aaaa 4\r\n"
				+ "aaad 4\r\n" + "aab 4\r\n" + "acad 4\r\n" + "acdc 4\r\n" + "ad 4\r\n" + "adad 4\r\n" + "b 4\r\n"
				+ "b 4\r\n" + "baa 4\r\n" + "bac 4\r\n" + "bba 4\r\n" + "bbaa 4\r\n" + "bbb 4\r\n" + "bc 4\r\n"
				+ "bdbc 4\r\n" + "c 4\r\n" + "ca 4\r\n" + "caaad 4\r\n" + "cbdb 4\r\n" + "cc 4\r\n" + "cca 4\r\n"
				+ "ccba 4\r\n" + "ccca 4\r\n" + "cccc 4\r\n" + "cdabd 4\r\n" + "cdbd 4\r\n" + "cdda 4\r\n" + "d 4\r\n"
				+ "d 4\r\n" + "d 4\r\n" + "da 4\r\n" + "daacb 4\r\n" + "dacda 4\r\n" + "dad 4\r\n" + "db 4\r\n"
				+ "dbb 4\r\n" + "dbbc 4\r\n" + "dbcdc 4\r\n" + "dccba 4\r\n" + "dd 4\r\n" + "ddccb 4\r\n" + "a 3\r\n"
				+ "a 3\r\n" + "a 3\r\n" + "aaaad 3\r\n" + "aad 3\r\n" + "acba 3\r\n" + "acd 3\r\n" + "ad 3\r\n"
				+ "addb 3\r\n" + "b 3\r\n" + "b 3\r\n" + "b 3\r\n" + "b 3\r\n" + "baac 3\r\n" + "bca 3\r\n"
				+ "bca 3\r\n" + "bcd 3\r\n" + "bd 3\r\n" + "caa 3\r\n" + "caaa 3\r\n" + "caac 3\r\n" + "cadcb 3\r\n"
				+ "cb 3\r\n" + "cbbac 3\r\n" + "cbdb 3\r\n" + "ccaac 3\r\n" + "ccbda 3\r\n" + "ccd 3\r\n"
				+ "cdaab 3\r\n" + "cdb 3\r\n" + "d 3\r\n" + "d 3\r\n" + "d 3\r\n" + "da 3\r\n" + "daaa 3\r\n"
				+ "dabc 3\r\n" + "dabc 3\r\n" + "dabc 3\r\n" + "dadca 3\r\n" + "dc 3\r\n" + "dccba 3\r\n" + "dcd 3\r\n"
				+ "dcddd 3\r\n" + "dddb 3\r\n" + "aaacd 2\r\n" + "aaddc 2\r\n" + "ab 2\r\n" + "acac 2\r\n"
				+ "accbd 2\r\n" + "adc 2\r\n" + "add 2\r\n" + "b 2\r\n" + "ba 2\r\n" + "bad 2\r\n" + "bb 2\r\n"
				+ "bbdb 2\r\n" + "bc 2\r\n" + "bdb 2\r\n" + "bdbc 2\r\n" + "ca 2\r\n" + "caabb 2\r\n" + "cbc 2\r\n"
				+ "cbdac 2\r\n" + "ccc 2\r\n" + "cdac 2\r\n" + "d 2\r\n" + "d 2\r\n" + "da 2\r\n" + "daaa 2\r\n"
				+ "daab 2\r\n" + "daba 2\r\n" + "dadcb 2\r\n" + "dbc 2\r\n" + "dcc 2\r\n" + "ddcd 2\r\n" + "a 1\r\n"
				+ "a 1\r\n" + "a 1\r\n" + "a 1\r\n" + "aaa 1\r\n" + "abac 1\r\n" + "abb 1\r\n" + "acaca 1\r\n"
				+ "adbd 1\r\n" + "adc 1\r\n" + "addc 1\r\n" + "b 1\r\n" + "ba 1\r\n" + "bb 1\r\n" + "bcad 1\r\n"
				+ "bd 1\r\n" + "bd 1\r\n" + "bdcdc 1\r\n" + "c 1\r\n" + "cacd 1\r\n" + "cad 1\r\n" + "cc 1\r\n"
				+ "cdc 1\r\n" + "d 1\r\n" + "daaba 1\r\n" + "dadbb 1\r\n" + "db 1\r\n" + "dbac 1\r\n" + "dbbad 1\r\n"
				+ "ddcc 1\r\n" + "a 0\r\n" + "a 0\r\n" + "a 0\r\n" + "aaaa 0\r\n" + "aabcd 0\r\n" + "aabd 0\r\n"
				+ "aacda 0\r\n" + "ab 0\r\n" + "abb 0\r\n" + "abbcc 0\r\n" + "abbcd 0\r\n" + "abc 0\r\n" + "acaac 0\r\n"
				+ "acbd 0\r\n" + "accb 0\r\n" + "acd 0\r\n" + "ad 0\r\n" + "adbd 0\r\n" + "b 0\r\n" + "b 0\r\n"
				+ "b 0\r\n" + "b 0\r\n" + "b 0\r\n" + "badaa 0\r\n" + "bbc 0\r\n" + "bcacc 0\r\n" + "bcd 0\r\n"
				+ "bcdad 0\r\n" + "bcdb 0\r\n" + "bd 0\r\n" + "bdacd 0\r\n" + "bdd 0\r\n" + "c 0\r\n" + "caac 0\r\n"
				+ "caccd 0\r\n" + "cbcac 0\r\n" + "cbddb 0\r\n" + "cc 0\r\n" + "cc 0\r\n" + "cd 0\r\n" + "cda 0\r\n"
				+ "cdac 0\r\n" + "cdd 0\r\n" + "d 0\r\n" + "d 0\r\n" + "d 0\r\n" + "d 0\r\n" + "dd 0\r\n" + "dd 0\r\n"
				+ "ddc 0");

		caseModelList.add(case1);
		caseModelList.add(case2);
		caseModelList.add(case3);
		CompileAndRun compileCode = new CompileAndRunImpl();
		runResultList = compileCode.RunCode("Solution", caseModelList);
		for (RunResult rr : runResultList) {
			System.out.println(rr.getResultCode() + " " + rr.getResultState());
		}
	}
}
